insert into employees (name, last_name, position, office, age, start_date) values ('Chrissie', 'Wasmer', 'Structural Engineer', 'China', 36, '2001-10-11');
insert into employees (name, last_name, position, office, age, start_date) values ('Laurianne', 'Meiklem', 'Programmer Analyst I', 'Finland', 54, '2010-04-22');
insert into employees (name, last_name, position, office, age, start_date) values ('Patrice', 'Tretwell', 'VP Marketing', 'Russia', 41, '1990-03-22');
insert into employees (name, last_name, position, office, age, start_date) values ('Peria', 'Parkins', 'Associate Professor', 'South Africa', 56, '2018-08-18');
insert into employees (name, last_name, position, office, age, start_date) values ('Rudie', 'Cummins', 'Nuclear Power Engineer', 'Georgia', 56, '2015-02-15');
insert into employees (name, last_name, position, office, age, start_date) values ('Baxie', 'Thorald', 'Associate Professor', 'China', 49, '1990-02-18');
insert into employees (name, last_name, position, office, age, start_date) values ('Lorenza', 'Milam', 'VP Product Management', 'Denmark', 25, '2010-12-24');
insert into employees (name, last_name, position, office, age, start_date) values ('Kirk', 'Salzen', 'Systems Administrator III', 'Israel', 49, '1989-01-20');
insert into employees (name, last_name, position, office, age, start_date) values ('Brietta', 'Ferbrache', 'Account Representative II', 'United States', 48, '1997-03-19');
insert into employees (name, last_name, position, office, age, start_date) values ('Kyle', 'Oxburgh', 'Marketing Manager', 'China', 64, '2003-08-16');
insert into employees (name, last_name, position, office, age, start_date) values ('Dorian', 'Meffin', 'Database Administrator IV', 'Costa Rica', 64, '2004-03-23');
insert into employees (name, last_name, position, office, age, start_date) values ('Shir', 'Lakeman', 'Developer I', 'Cyprus', 47, '2004-04-25');
insert into employees (name, last_name, position, office, age, start_date) values ('Rebekkah', 'Archbould', 'Assistant Manager', 'Chile', 39, '1992-04-25');
insert into employees (name, last_name, position, office, age, start_date) values ('Letty', 'Clohissy', 'Senior Cost Accountant', 'Iran', 30, '1999-11-11');
insert into employees (name, last_name, position, office, age, start_date) values ('Viola', 'Mariault', 'Geological Engineer', 'Canada', 60, '2012-10-13');
insert into employees (name, last_name, position, office, age, start_date) values ('Janis', 'Michelet', 'Senior Financial Analyst', 'Sweden', 61, '2002-04-09');
insert into employees (name, last_name, position, office, age, start_date) values ('Aland', 'Dreossi', 'Accountant I', 'Indonesia', 43, '2009-12-05');
insert into employees (name, last_name, position, office, age, start_date) values ('Rickie', 'Pauli', 'Nuclear Power Engineer', 'China', 37, '2013-11-13');
insert into employees (name, last_name, position, office, age, start_date) values ('Peggy', 'Billows', 'Account Representative IV', 'Venezuela', 62, '1988-07-12');
insert into employees (name, last_name, position, office, age, start_date) values ('Auberon', 'Stockow', 'Electrical Engineer', 'Russia', 31, '2012-08-02');
insert into employees (name, last_name, position, office, age, start_date) values ('Diann', 'Sharple', 'Speech Pathologist', 'Indonesia', 28, '2003-05-09');
insert into employees (name, last_name, position, office, age, start_date) values ('Rolfe', 'Muff', 'Sales Associate', 'China', 37, '2016-04-20');
insert into employees (name, last_name, position, office, age, start_date) values ('Piper', 'Culham', 'Assistant Media Planner', 'China', 44, '2017-02-21');
insert into employees (name, last_name, position, office, age, start_date) values ('Joanna', 'Yerrall', 'Sales Associate', 'Brazil', 55, '1987-11-12');
insert into employees (name, last_name, position, office, age, start_date) values ('Vaclav', 'Viner', 'Programmer IV', 'Belarus', 49, '1989-07-18');
insert into employees (name, last_name, position, office, age, start_date) values ('Whitman', 'Qualtro', 'Marketing Assistant', 'Indonesia', 57, '2017-03-06');
insert into employees (name, last_name, position, office, age, start_date) values ('Kirk', 'Zamorano', 'Nurse', 'Palestinian Territory', 47, '1987-02-28');
insert into employees (name, last_name, position, office, age, start_date) values ('Ali', 'Passe', 'Financial Analyst', 'United States', 44, '2017-12-03');
insert into employees (name, last_name, position, office, age, start_date) values ('Quintin', 'Treen', 'Assistant Professor', 'Honduras', 62, '2006-03-07');
insert into employees (name, last_name, position, office, age, start_date) values ('Moyra', 'Deverille', 'Payment Adjustment Coordinator', 'China', 35, '2001-03-25');
insert into employees (name, last_name, position, office, age, start_date) values ('Kin', 'Padbery', 'Sales Representative', 'Indonesia', 63, '2016-09-29');
insert into employees (name, last_name, position, office, age, start_date) values ('Tomi', 'Bethell', 'Electrical Engineer', 'Egypt', 34, '2011-02-23');
insert into employees (name, last_name, position, office, age, start_date) values ('Cristine', 'Formilli', 'Senior Quality Engineer', 'Brazil', 40, '2010-07-08');
insert into employees (name, last_name, position, office, age, start_date) values ('Malinde', 'Millington', 'Product Engineer', 'Yemen', 32, '1998-07-20');
insert into employees (name, last_name, position, office, age, start_date) values ('Christy', 'Caulton', 'Graphic Designer', 'Peru', 45, '2011-12-27');
insert into employees (name, last_name, position, office, age, start_date) values ('Ruperto', 'Lovick', 'Accountant I', 'Russia', 47, '2005-11-23');
insert into employees (name, last_name, position, office, age, start_date) values ('Manya', 'Kiehl', 'Developer I', 'Saudi Arabia', 32, '2010-03-18');
insert into employees (name, last_name, position, office, age, start_date) values ('Rici', 'Mc Gee', 'Community Outreach Specialist', 'China', 51, '2003-05-16');
insert into employees (name, last_name, position, office, age, start_date) values ('Mollie', 'Iorizzo', 'Senior Financial Analyst', 'Brazil', 31, '2009-08-25');
insert into employees (name, last_name, position, office, age, start_date) values ('Jeanne', 'Broadbere', 'Help Desk Operator', 'Russia', 26, '2002-11-04');
insert into employees (name, last_name, position, office, age, start_date) values ('Nessi', 'Haggart', 'Computer Systems Analyst IV', 'Indonesia', 32, '2005-06-06');
insert into employees (name, last_name, position, office, age, start_date) values ('Morse', 'Egle', 'Pharmacist', 'Peru', 37, '2003-04-17');
insert into employees (name, last_name, position, office, age, start_date) values ('Ingram', 'Stoffer', 'Staff Accountant II', 'Malaysia', 27, '2013-03-01');
insert into employees (name, last_name, position, office, age, start_date) values ('Kellsie', 'Byas', 'Help Desk Operator', 'China', 60, '1988-05-12');
insert into employees (name, last_name, position, office, age, start_date) values ('Chrissie', 'Barbosa', 'Administrative Assistant I', 'Thailand', 35, '2014-06-27');
insert into employees (name, last_name, position, office, age, start_date) values ('Lanna', 'Hugonin', 'Software Engineer III', 'Portugal', 49, '2007-09-05');
insert into employees (name, last_name, position, office, age, start_date) values ('Ingelbert', 'Willgress', 'Graphic Designer', 'Philippines', 27, '1990-11-12');
insert into employees (name, last_name, position, office, age, start_date) values ('Britni', 'Coatsworth', 'Senior Quality Engineer', 'Georgia', 52, '2009-04-04');
insert into employees (name, last_name, position, office, age, start_date) values ('Cahra', 'Sterland', 'Data Coordiator', 'China', 48, '1994-10-06');
insert into employees (name, last_name, position, office, age, start_date) values ('Gerry', 'Meharg', 'Design Engineer', 'Czech Republic', 56, '1987-01-21');
insert into employees (name, last_name, position, office, age, start_date) values ('Rich', 'Treven', 'Administrative Assistant II', 'Thailand', 30, '2004-09-10');
insert into employees (name, last_name, position, office, age, start_date) values ('Patricio', 'Haresnaip', 'Recruiting Manager', 'Lithuania', 59, '2018-05-28');
insert into employees (name, last_name, position, office, age, start_date) values ('Kippar', 'Gallacher', 'Structural Analysis Engineer', 'Russia', 63, '1994-03-27');
insert into employees (name, last_name, position, office, age, start_date) values ('Bonni', 'Gelling', 'Human Resources Assistant I', 'Argentina', 29, '2003-12-02');
insert into employees (name, last_name, position, office, age, start_date) values ('Antonie', 'Plinck', 'Recruiter', 'Nigeria', 61, '1990-12-10');
insert into employees (name, last_name, position, office, age, start_date) values ('Fitz', 'Philippeaux', 'Computer Systems Analyst II', 'Brazil', 41, '2015-05-26');
insert into employees (name, last_name, position, office, age, start_date) values ('Karim', 'Guilloneau', 'Speech Pathologist', 'China', 37, '1998-11-27');
insert into employees (name, last_name, position, office, age, start_date) values ('Paddie', 'Scroyton', 'Electrical Engineer', 'Colombia', 31, '2020-08-11');
insert into employees (name, last_name, position, office, age, start_date) values ('Robina', 'O''Lenane', 'Developer II', 'Yemen', 63, '2013-02-12');
insert into employees (name, last_name, position, office, age, start_date) values ('Susann', 'McArthur', 'Engineer II', 'Armenia', 58, '2017-01-12');
insert into employees (name, last_name, position, office, age, start_date) values ('Rod', 'Boston', 'Help Desk Operator', 'Brazil', 49, '2016-10-31');
insert into employees (name, last_name, position, office, age, start_date) values ('Harman', 'Showte', 'Cost Accountant', 'United Kingdom', 59, '2004-09-06');
insert into employees (name, last_name, position, office, age, start_date) values ('Deeyn', 'Losbie', 'Staff Accountant I', 'Thailand', 50, '1988-11-08');
insert into employees (name, last_name, position, office, age, start_date) values ('Berkie', 'Wilks', 'VP Accounting', 'United States', 54, '1994-04-15');
insert into employees (name, last_name, position, office, age, start_date) values ('Quincy', 'Reen', 'Senior Financial Analyst', 'Tunisia', 30, '2005-01-18');
insert into employees (name, last_name, position, office, age, start_date) values ('Veronika', 'Kippen', 'Budget/Accounting Analyst I', 'Greece', 61, '2016-06-24');
insert into employees (name, last_name, position, office, age, start_date) values ('Lucais', 'Cribbin', 'Marketing Manager', 'Portugal', 28, '2004-11-16');
insert into employees (name, last_name, position, office, age, start_date) values ('Nan', 'Willbourne', 'Software Test Engineer II', 'Egypt', 51, '2010-05-24');
insert into employees (name, last_name, position, office, age, start_date) values ('Lissa', 'Congram', 'Recruiter', 'Ukraine', 26, '2013-02-03');
insert into employees (name, last_name, position, office, age, start_date) values ('Johnna', 'Quant', 'Food Chemist', 'Bolivia', 52, '1996-06-18');
insert into employees (name, last_name, position, office, age, start_date) values ('Jon', 'Blincow', 'Administrative Assistant IV', 'Slovenia', 47, '2002-05-19');
insert into employees (name, last_name, position, office, age, start_date) values ('Emmanuel', 'Bunyard', 'Electrical Engineer', 'Indonesia', 44, '2004-04-11');
insert into employees (name, last_name, position, office, age, start_date) values ('Connie', 'Connar', 'VP Product Management', 'Indonesia', 61, '2009-04-05');
insert into employees (name, last_name, position, office, age, start_date) values ('Ofelia', 'Frarey', 'Web Designer II', 'Mexico', 53, '1985-08-30');
insert into employees (name, last_name, position, office, age, start_date) values ('Rosmunda', 'Darlison', 'Health Coach I', 'Thailand', 55, '2017-10-15');
insert into employees (name, last_name, position, office, age, start_date) values ('Helaine', 'Ybarra', 'Associate Professor', 'Peru', 64, '2001-11-03');
insert into employees (name, last_name, position, office, age, start_date) values ('Reyna', 'MacCafferty', 'Professor', 'Indonesia', 25, '1995-06-09');
insert into employees (name, last_name, position, office, age, start_date) values ('Winnie', 'Mussilli', 'Business Systems Development Analyst', 'Morocco', 26, '2007-11-22');
insert into employees (name, last_name, position, office, age, start_date) values ('Daron', 'Joint', 'Senior Sales Associate', 'Armenia', 29, '1986-04-02');
insert into employees (name, last_name, position, office, age, start_date) values ('Simon', 'Barwis', 'Cost Accountant', 'Indonesia', 51, '2001-06-12');
insert into employees (name, last_name, position, office, age, start_date) values ('Darlleen', 'Hartop', 'Financial Advisor', 'Philippines', 44, '1988-07-16');
insert into employees (name, last_name, position, office, age, start_date) values ('Ambros', 'Stenson', 'Quality Engineer', 'China', 54, '2009-11-07');
insert into employees (name, last_name, position, office, age, start_date) values ('Oswald', 'Pedrozzi', 'Automation Specialist I', 'Philippines', 40, '2014-12-08');
insert into employees (name, last_name, position, office, age, start_date) values ('Marianne', 'Booth', 'Research Nurse', 'Peru', 49, '1986-12-18');
insert into employees (name, last_name, position, office, age, start_date) values ('Brenn', 'Pettinger', 'Account Representative III', 'Poland', 47, '2004-02-27');
insert into employees (name, last_name, position, office, age, start_date) values ('Lorine', 'Broome', 'Accounting Assistant IV', 'Philippines', 58, '1991-10-22');
insert into employees (name, last_name, position, office, age, start_date) values ('Shay', 'Jutson', 'Administrative Officer', 'Indonesia', 48, '1990-07-23');
insert into employees (name, last_name, position, office, age, start_date) values ('Averil', 'Julien', 'Data Coordiator', 'Poland', 28, '1987-10-30');
insert into employees (name, last_name, position, office, age, start_date) values ('Warden', 'Roskrug', 'Information Systems Manager', 'Mexico', 58, '2017-01-25');
insert into employees (name, last_name, position, office, age, start_date) values ('Gwendolin', 'Colebrook', 'Nuclear Power Engineer', 'Sweden', 35, '2010-06-12');
insert into employees (name, last_name, position, office, age, start_date) values ('Cherri', 'Degan', 'Graphic Designer', 'Czech Republic', 43, '2002-02-12');
insert into employees (name, last_name, position, office, age, start_date) values ('Shanta', 'Petrina', 'Account Coordinator', 'Indonesia', 52, '2011-02-16');
insert into employees (name, last_name, position, office, age, start_date) values ('Zelma', 'Hatchard', 'Staff Scientist', 'Greece', 57, '1987-09-20');
insert into employees (name, last_name, position, office, age, start_date) values ('Ogdon', 'Arent', 'Structural Analysis Engineer', 'Honduras', 57, '2005-01-09');
insert into employees (name, last_name, position, office, age, start_date) values ('Emelda', 'Chansonnau', 'Web Developer IV', 'Canada', 60, '1995-01-03');
insert into employees (name, last_name, position, office, age, start_date) values ('Brina', 'Moorton', 'Help Desk Technician', 'South Korea', 36, '2004-05-21');
insert into employees (name, last_name, position, office, age, start_date) values ('Karil', 'Kleis', 'General Manager', 'Swaziland', 45, '2017-03-08');
insert into employees (name, last_name, position, office, age, start_date) values ('Lelia', 'Alenikov', 'Quality Control Specialist', 'Armenia', 41, '1990-09-14');
insert into employees (name, last_name, position, office, age, start_date) values ('Steven', 'Vasyutichev', 'Community Outreach Specialist', 'Czech Republic', 27, '1999-05-15');
insert into employees (name, last_name, position, office, age, start_date) values ('Townsend', 'Withams', 'Developer IV', 'China', 55, '2001-03-20');
insert into employees (name, last_name, position, office, age, start_date) values ('Nedda', 'Knowller', 'Clinical Specialist', 'Indonesia', 52, '1997-11-15');
insert into employees (name, last_name, position, office, age, start_date) values ('Darcy', 'Huxley', 'Programmer Analyst II', 'Pakistan', 45, '2018-08-23');
insert into employees (name, last_name, position, office, age, start_date) values ('Sophi', 'Wilford', 'Senior Cost Accountant', 'Indonesia', 43, '2014-03-21');
insert into employees (name, last_name, position, office, age, start_date) values ('Cynthie', 'Smalls', 'Systems Administrator III', 'Brazil', 35, '1995-02-22');
insert into employees (name, last_name, position, office, age, start_date) values ('Emmery', 'Tallach', 'Assistant Professor', 'Sweden', 42, '1994-07-14');
insert into employees (name, last_name, position, office, age, start_date) values ('Debee', 'Hedge', 'Senior Quality Engineer', 'China', 30, '2008-10-08');
insert into employees (name, last_name, position, office, age, start_date) values ('Monty', 'Gate', 'VP Product Management', 'Russia', 64, '1996-04-01');
insert into employees (name, last_name, position, office, age, start_date) values ('Marjorie', 'Slidders', 'Web Developer I', 'Japan', 65, '2011-10-21');
insert into employees (name, last_name, position, office, age, start_date) values ('Philippe', 'Sabey', 'Chief Design Engineer', 'Peru', 35, '1991-03-21');
insert into employees (name, last_name, position, office, age, start_date) values ('Brittani', 'Drance', 'Research Nurse', 'Portugal', 49, '1997-02-10');
insert into employees (name, last_name, position, office, age, start_date) values ('Omero', 'Poser', 'Automation Specialist I', 'Brazil', 51, '2010-09-04');
insert into employees (name, last_name, position, office, age, start_date) values ('Layla', 'Bootyman', 'Geologist I', 'Czech Republic', 43, '2017-01-15');
insert into employees (name, last_name, position, office, age, start_date) values ('Maximo', 'Breewood', 'Safety Technician I', 'Ireland', 41, '2014-01-12');
insert into employees (name, last_name, position, office, age, start_date) values ('West', 'Lafoy', 'Director of Sales', 'Slovenia', 54, '2007-10-11');
insert into employees (name, last_name, position, office, age, start_date) values ('Melita', 'Wass', 'Data Coordiator', 'Ukraine', 63, '1992-05-12');
insert into employees (name, last_name, position, office, age, start_date) values ('Minni', 'Schindler', 'Nurse Practicioner', 'Australia', 62, '1989-10-17');
insert into employees (name, last_name, position, office, age, start_date) values ('Jarrod', 'Haps', 'Community Outreach Specialist', 'China', 46, '2003-07-15');
insert into employees (name, last_name, position, office, age, start_date) values ('Dewey', 'Jobbings', 'Database Administrator II', 'Indonesia', 31, '2014-01-30');
insert into employees (name, last_name, position, office, age, start_date) values ('Almeda', 'Scarlett', 'Web Designer III', 'Philippines', 43, '2013-01-11');
insert into employees (name, last_name, position, office, age, start_date) values ('Viva', 'Idale', 'Assistant Media Planner', 'Russia', 55, '2000-05-21');
insert into employees (name, last_name, position, office, age, start_date) values ('Britney', 'Hadwin', 'Account Executive', 'China', 41, '2002-07-19');
insert into employees (name, last_name, position, office, age, start_date) values ('Liana', 'McGraffin', 'Web Developer III', 'Botswana', 63, '1997-10-29');
insert into employees (name, last_name, position, office, age, start_date) values ('Mindy', 'Dallemore', 'Chemical Engineer', 'China', 38, '2020-05-04');
insert into employees (name, last_name, position, office, age, start_date) values ('Delphinia', 'Selburn', 'Account Executive', 'China', 39, '2014-05-20');
insert into employees (name, last_name, position, office, age, start_date) values ('Salomo', 'Gurton', 'Biostatistician I', 'Mexico', 46, '2009-08-02');
insert into employees (name, last_name, position, office, age, start_date) values ('Vito', 'Owen', 'VP Marketing', 'China', 25, '1985-10-16');
insert into employees (name, last_name, position, office, age, start_date) values ('Kean', 'Heugh', 'Registered Nurse', 'Peru', 44, '2009-08-18');
insert into employees (name, last_name, position, office, age, start_date) values ('Shalom', 'Cometti', 'Marketing Manager', 'Poland', 60, '1986-05-11');
insert into employees (name, last_name, position, office, age, start_date) values ('Bartholomew', 'Brimblecomb', 'Developer IV', 'Russia', 54, '2008-06-19');
insert into employees (name, last_name, position, office, age, start_date) values ('Glynis', 'Carlow', 'Structural Engineer', 'Brazil', 41, '1988-12-04');
insert into employees (name, last_name, position, office, age, start_date) values ('Dot', 'Hooke', 'Paralegal', 'Philippines', 61, '2003-02-11');
insert into employees (name, last_name, position, office, age, start_date) values ('Hedvige', 'LeEstut', 'Senior Cost Accountant', 'China', 47, '1996-07-21');
insert into employees (name, last_name, position, office, age, start_date) values ('Dacey', 'Itzhayek', 'Database Administrator I', 'Philippines', 34, '1993-04-10');
insert into employees (name, last_name, position, office, age, start_date) values ('Lothaire', 'Gentner', 'Data Coordiator', 'Philippines', 33, '2019-07-08');
insert into employees (name, last_name, position, office, age, start_date) values ('Torry', 'Bentjens', 'Human Resources Assistant IV', 'Greece', 65, '2014-08-13');
insert into employees (name, last_name, position, office, age, start_date) values ('Jaine', 'Hallstone', 'Accountant II', 'Colombia', 26, '1986-11-21');
insert into employees (name, last_name, position, office, age, start_date) values ('Barny', 'Ivic', 'General Manager', 'Brazil', 50, '2020-03-20');
insert into employees (name, last_name, position, office, age, start_date) values ('Trix', 'Pappi', 'Clinical Specialist', 'Bulgaria', 52, '1997-02-19');
insert into employees (name, last_name, position, office, age, start_date) values ('Laird', 'Grono', 'Senior Financial Analyst', 'China', 28, '2011-02-15');
insert into employees (name, last_name, position, office, age, start_date) values ('Hayden', 'Stonham', 'Statistician IV', 'Argentina', 54, '1991-02-16');
insert into employees (name, last_name, position, office, age, start_date) values ('Callida', 'Delahunty', 'Electrical Engineer', 'China', 35, '2008-05-11');
insert into employees (name, last_name, position, office, age, start_date) values ('Mikael', 'Madle', 'Executive Secretary', 'Namibia', 47, '2006-10-25');
insert into employees (name, last_name, position, office, age, start_date) values ('Seumas', 'Carvell', 'Analog Circuit Design manager', 'Spain', 62, '1992-02-28');
insert into employees (name, last_name, position, office, age, start_date) values ('Sayre', 'Hawkes', 'Account Executive', 'Russia', 33, '1993-07-13');
insert into employees (name, last_name, position, office, age, start_date) values ('Barbey', 'Pinke', 'Budget/Accounting Analyst IV', 'Israel', 59, '2000-12-04');
insert into employees (name, last_name, position, office, age, start_date) values ('Ellissa', 'Mugg', 'Programmer IV', 'Moldova', 27, '1991-10-28');
insert into employees (name, last_name, position, office, age, start_date) values ('Zora', 'Kenefick', 'Developer II', 'Canada', 29, '1991-04-18');
insert into employees (name, last_name, position, office, age, start_date) values ('Ashlin', 'Cushion', 'Sales Representative', 'Afghanistan', 62, '2006-09-20');
insert into employees (name, last_name, position, office, age, start_date) values ('Silvan', 'Ings', 'Sales Representative', 'Indonesia', 49, '2011-10-24');
insert into employees (name, last_name, position, office, age, start_date) values ('Kristien', 'Benjamin', 'General Manager', 'Indonesia', 36, '1988-04-27');
insert into employees (name, last_name, position, office, age, start_date) values ('Lane', 'Boulstridge', 'Financial Advisor', 'Poland', 37, '2019-05-15');
insert into employees (name, last_name, position, office, age, start_date) values ('Wald', 'Johansson', 'Safety Technician III', 'Honduras', 45, '2014-03-23');
insert into employees (name, last_name, position, office, age, start_date) values ('Teodorico', 'Lyffe', 'Safety Technician III', 'Philippines', 62, '1991-05-22');
insert into employees (name, last_name, position, office, age, start_date) values ('Jeffy', 'Torre', 'Developer III', 'China', 27, '1987-02-13');
insert into employees (name, last_name, position, office, age, start_date) values ('Lucita', 'Andreotti', 'Payment Adjustment Coordinator', 'Dominican Republic', 37, '1989-12-13');
insert into employees (name, last_name, position, office, age, start_date) values ('Gabi', 'Ibbitson', 'Senior Quality Engineer', 'China', 64, '1995-11-20');
insert into employees (name, last_name, position, office, age, start_date) values ('Ky', 'Gadsden', 'Structural Analysis Engineer', 'Honduras', 26, '1992-02-11');
insert into employees (name, last_name, position, office, age, start_date) values ('Kerr', 'Nipper', 'Business Systems Development Analyst', 'Kenya', 33, '1997-08-16');
insert into employees (name, last_name, position, office, age, start_date) values ('Burnaby', 'Farlane', 'Director of Sales', 'Honduras', 42, '2011-03-15');
insert into employees (name, last_name, position, office, age, start_date) values ('Ulrikaumeko', 'Bissett', 'Staff Accountant III', 'Argentina', 51, '2002-11-19');
insert into employees (name, last_name, position, office, age, start_date) values ('Kendell', 'Winsper', 'Nuclear Power Engineer', 'Spain', 38, '2005-09-15');
insert into employees (name, last_name, position, office, age, start_date) values ('Sander', 'Wickmann', 'Safety Technician IV', 'Poland', 60, '2005-12-28');
insert into employees (name, last_name, position, office, age, start_date) values ('Biddie', 'Lindenbaum', 'Accounting Assistant III', 'China', 45, '2006-03-21');
insert into employees (name, last_name, position, office, age, start_date) values ('Geneva', 'Fazakerley', 'Geologist III', 'Nepal', 44, '2019-12-13');
insert into employees (name, last_name, position, office, age, start_date) values ('Tadio', 'Maharry', 'Financial Advisor', 'China', 57, '2002-01-13');
insert into employees (name, last_name, position, office, age, start_date) values ('Theobald', 'Akast', 'Compensation Analyst', 'Japan', 29, '2018-08-13');
insert into employees (name, last_name, position, office, age, start_date) values ('Arliene', 'Willerstone', 'Associate Professor', 'Argentina', 30, '2010-01-18');
insert into employees (name, last_name, position, office, age, start_date) values ('Lanna', 'Grealy', 'Engineer II', 'Indonesia', 58, '2007-11-23');
insert into employees (name, last_name, position, office, age, start_date) values ('Elvina', 'Filyaev', 'Assistant Media Planner', 'Portugal', 46, '2001-06-09');
insert into employees (name, last_name, position, office, age, start_date) values ('Joelynn', 'Sunners', 'Help Desk Technician', 'China', 45, '2001-01-21');
insert into employees (name, last_name, position, office, age, start_date) values ('Lanita', 'Chick', 'Marketing Assistant', 'Colombia', 38, '1998-01-28');
insert into employees (name, last_name, position, office, age, start_date) values ('Gaby', 'Hillett', 'Software Consultant', 'Mexico', 47, '1996-09-10');
insert into employees (name, last_name, position, office, age, start_date) values ('Cinda', 'Gilleon', 'Design Engineer', 'China', 31, '1997-05-29');
insert into employees (name, last_name, position, office, age, start_date) values ('Annabel', 'Pidgen', 'Automation Specialist IV', 'Czech Republic', 44, '2012-10-23');
insert into employees (name, last_name, position, office, age, start_date) values ('Barth', 'Essame', 'Data Coordiator', 'Guatemala', 34, '2009-09-04');
insert into employees (name, last_name, position, office, age, start_date) values ('Katuscha', 'Backman', 'Accountant III', 'China', 32, '2009-02-06');
insert into employees (name, last_name, position, office, age, start_date) values ('Maureen', 'Robbie', 'Research Assistant I', 'Armenia', 30, '2016-04-27');
insert into employees (name, last_name, position, office, age, start_date) values ('Abrahan', 'Malone', 'Nurse', 'New Zealand', 34, '1991-12-13');
insert into employees (name, last_name, position, office, age, start_date) values ('Dewey', 'Cluett', 'Human Resources Assistant II', 'Poland', 56, '2000-07-30');
insert into employees (name, last_name, position, office, age, start_date) values ('Linda', 'Reading', 'Web Developer I', 'Indonesia', 55, '2007-02-27');
insert into employees (name, last_name, position, office, age, start_date) values ('Kippie', 'Mattheissen', 'Software Consultant', 'Czech Republic', 58, '1993-08-31');
insert into employees (name, last_name, position, office, age, start_date) values ('Wynne', 'Foulsham', 'Senior Quality Engineer', 'Canada', 63, '2020-01-31');
insert into employees (name, last_name, position, office, age, start_date) values ('Alice', 'Westoll', 'Software Test Engineer II', 'China', 46, '2000-08-31');
insert into employees (name, last_name, position, office, age, start_date) values ('Terra', 'Morison', 'Programmer II', 'Vietnam', 49, '2012-11-02');
insert into employees (name, last_name, position, office, age, start_date) values ('Mathew', 'Lettsom', 'Speech Pathologist', 'Russia', 61, '1995-01-19');
insert into employees (name, last_name, position, office, age, start_date) values ('Jacquelyn', 'Pestor', 'Electrical Engineer', 'China', 25, '1992-03-17');
insert into employees (name, last_name, position, office, age, start_date) values ('Astrid', 'Bexley', 'Clinical Specialist', 'Indonesia', 29, '2002-01-07');
insert into employees (name, last_name, position, office, age, start_date) values ('Wayne', 'Vardie', 'Civil Engineer', 'Russia', 39, '2008-11-17');
insert into employees (name, last_name, position, office, age, start_date) values ('Sollie', 'Filipov', 'Human Resources Assistant IV', 'Poland', 61, '1985-09-07');
insert into employees (name, last_name, position, office, age, start_date) values ('Les', 'Glyssanne', 'Recruiting Manager', 'Indonesia', 55, '2005-07-01');
insert into employees (name, last_name, position, office, age, start_date) values ('Rik', 'Seymark', 'VP Marketing', 'Philippines', 49, '2014-09-02');
insert into employees (name, last_name, position, office, age, start_date) values ('Sibilla', 'Thomkins', 'Engineer III', 'Russia', 65, '2004-01-08');
insert into employees (name, last_name, position, office, age, start_date) values ('Angelo', 'Rapelli', 'Accountant IV', 'Philippines', 30, '2009-02-17');
insert into employees (name, last_name, position, office, age, start_date) values ('Emelita', 'Meriott', 'Food Chemist', 'Nepal', 37, '1987-11-28');
insert into employees (name, last_name, position, office, age, start_date) values ('Philippe', 'Jevons', 'Office Assistant III', 'Russia', 32, '2011-07-18');
insert into employees (name, last_name, position, office, age, start_date) values ('Camey', 'Pound', 'Actuary', 'Ivory Coast', 60, '2002-07-13');
insert into employees (name, last_name, position, office, age, start_date) values ('Britney', 'Sarra', 'Web Developer II', 'Chile', 49, '2001-09-17');
insert into employees (name, last_name, position, office, age, start_date) values ('Pieter', 'Mary', 'Marketing Manager', 'Philippines', 54, '2018-05-20');
insert into employees (name, last_name, position, office, age, start_date) values ('Evelyn', 'Ebenezer', 'Research Nurse', 'Ecuador', 44, '2006-06-03');
insert into employees (name, last_name, position, office, age, start_date) values ('Tarah', 'Dunning', 'Environmental Specialist', 'Moldova', 45, '2019-06-03');
insert into employees (name, last_name, position, office, age, start_date) values ('Vallie', 'Loins', 'Information Systems Manager', 'Canada', 32, '2010-05-17');
insert into employees (name, last_name, position, office, age, start_date) values ('Hannah', 'Keitch', 'Research Nurse', 'Pakistan', 51, '1994-09-26');
insert into employees (name, last_name, position, office, age, start_date) values ('Nick', 'Hunnicot', 'Executive Secretary', 'China', 58, '2004-01-15');
insert into employees (name, last_name, position, office, age, start_date) values ('Sebastiano', 'Otson', 'Junior Executive', 'Russia', 65, '1998-06-01');
insert into employees (name, last_name, position, office, age, start_date) values ('Chip', 'McGowing', 'Chemical Engineer', 'France', 59, '2001-05-06');
insert into employees (name, last_name, position, office, age, start_date) values ('Caryn', 'Restieaux', 'Assistant Professor', 'Bolivia', 59, '1998-06-03');
insert into employees (name, last_name, position, office, age, start_date) values ('Cullie', 'Grinin', 'Sales Associate', 'Indonesia', 34, '2003-10-31');
insert into employees (name, last_name, position, office, age, start_date) values ('Phaedra', 'Waiting', 'Staff Scientist', 'United States', 64, '2018-02-10');
insert into employees (name, last_name, position, office, age, start_date) values ('Reynolds', 'Mariyushkin', 'Associate Professor', 'China', 26, '2011-06-16');
insert into employees (name, last_name, position, office, age, start_date) values ('Porter', 'Elder', 'VP Product Management', 'China', 64, '2014-01-06');
insert into employees (name, last_name, position, office, age, start_date) values ('Chery', 'Dikles', 'Legal Assistant', 'Kyrgyzstan', 62, '2008-10-28');
insert into employees (name, last_name, position, office, age, start_date) values ('Gasparo', 'Micka', 'Payment Adjustment Coordinator', 'Indonesia', 56, '2004-09-29');
insert into employees (name, last_name, position, office, age, start_date) values ('Eadmund', 'Gildea', 'Project Manager', 'Portugal', 46, '2012-11-29');
insert into employees (name, last_name, position, office, age, start_date) values ('Gordie', 'Chapell', 'Legal Assistant', 'Poland', 64, '2000-01-05');
insert into employees (name, last_name, position, office, age, start_date) values ('Kayla', 'McCowan', 'Assistant Media Planner', 'Serbia', 45, '2018-09-13');
insert into employees (name, last_name, position, office, age, start_date) values ('Edan', 'Eastop', 'Web Designer I', 'Russia', 45, '2015-05-17');
insert into employees (name, last_name, position, office, age, start_date) values ('Waldemar', 'Argue', 'Clinical Specialist', 'Russia', 64, '1991-11-29');
insert into employees (name, last_name, position, office, age, start_date) values ('Reuven', 'Mannie', 'Librarian', 'Uzbekistan', 36, '1995-05-03');
insert into employees (name, last_name, position, office, age, start_date) values ('Hobie', 'Baynham', 'Database Administrator I', 'Philippines', 28, '1987-06-13');
insert into employees (name, last_name, position, office, age, start_date) values ('Calhoun', 'McCreath', 'Librarian', 'United States', 53, '1986-09-16');
insert into employees (name, last_name, position, office, age, start_date) values ('Carlo', 'Pickavance', 'Accounting Assistant I', 'Russia', 44, '2005-05-17');
insert into employees (name, last_name, position, office, age, start_date) values ('Gustaf', 'Maine', 'Health Coach I', 'Mauritius', 48, '1992-09-11');
insert into employees (name, last_name, position, office, age, start_date) values ('Katrine', 'Ruttgers', 'Teacher', 'Palestinian Territory', 30, '1999-11-02');
insert into employees (name, last_name, position, office, age, start_date) values ('Christopher', 'Unstead', 'Senior Quality Engineer', 'Philippines', 26, '2012-07-29');
insert into employees (name, last_name, position, office, age, start_date) values ('Harmon', 'Thewlis', 'Help Desk Technician', 'Poland', 37, '1996-10-10');
insert into employees (name, last_name, position, office, age, start_date) values ('Whitney', 'Coulman', 'Clinical Specialist', 'Mongolia', 42, '2001-04-23');
insert into employees (name, last_name, position, office, age, start_date) values ('Elysia', 'McCerery', 'Media Manager IV', 'Indonesia', 31, '2010-10-14');
insert into employees (name, last_name, position, office, age, start_date) values ('Vikki', 'Guise', 'Engineer III', 'Montenegro', 65, '2011-05-13');
insert into employees (name, last_name, position, office, age, start_date) values ('Glenden', 'O''Rodane', 'Environmental Tech', 'Egypt', 27, '1987-02-28');
insert into employees (name, last_name, position, office, age, start_date) values ('Doroteya', 'Kilfoyle', 'Nuclear Power Engineer', 'Indonesia', 42, '2002-03-06');
insert into employees (name, last_name, position, office, age, start_date) values ('Heath', 'Adshead', 'Editor', 'Sri Lanka', 47, '1995-11-16');
insert into employees (name, last_name, position, office, age, start_date) values ('Annnora', 'Mathiot', 'Civil Engineer', 'Dominican Republic', 61, '1998-09-29');
insert into employees (name, last_name, position, office, age, start_date) values ('Munroe', 'Dukesbury', 'Web Designer II', 'France', 28, '1997-02-09');
insert into employees (name, last_name, position, office, age, start_date) values ('Bride', 'Fieller', 'Staff Scientist', 'China', 47, '2020-04-16');
insert into employees (name, last_name, position, office, age, start_date) values ('Merci', 'Sieur', 'Executive Secretary', 'China', 30, '1988-01-15');
insert into employees (name, last_name, position, office, age, start_date) values ('Valerie', 'Marte', 'VP Product Management', 'Finland', 30, '2013-09-27');
insert into employees (name, last_name, position, office, age, start_date) values ('Katrine', 'Willcox', 'Civil Engineer', 'Colombia', 33, '1990-02-19');
insert into employees (name, last_name, position, office, age, start_date) values ('Margot', 'Chevins', 'Structural Engineer', 'Poland', 37, '1987-05-20');
insert into employees (name, last_name, position, office, age, start_date) values ('Dasya', 'Seebert', 'Financial Advisor', 'Venezuela', 48, '2005-01-22');
insert into employees (name, last_name, position, office, age, start_date) values ('Prudy', 'Casbourne', 'Sales Representative', 'China', 45, '2007-06-04');
insert into employees (name, last_name, position, office, age, start_date) values ('Elsie', 'Gheorghescu', 'Account Coordinator', 'China', 41, '1986-02-15');
insert into employees (name, last_name, position, office, age, start_date) values ('Ricard', 'MacParlan', 'Business Systems Development Analyst', 'Azerbaijan', 64, '1988-11-03');
insert into employees (name, last_name, position, office, age, start_date) values ('William', 'Wolfart', 'GIS Technical Architect', 'Philippines', 48, '1995-01-05');
insert into employees (name, last_name, position, office, age, start_date) values ('Alisander', 'Martinelli', 'Junior Executive', 'Ukraine', 37, '2007-03-03');
insert into employees (name, last_name, position, office, age, start_date) values ('Shaun', 'Heading', 'Staff Accountant II', 'Colombia', 46, '1986-05-30');
insert into employees (name, last_name, position, office, age, start_date) values ('Ken', 'Gann', 'Senior Cost Accountant', 'Nicaragua', 36, '1986-07-04');
insert into employees (name, last_name, position, office, age, start_date) values ('Dorita', 'Mussen', 'Information Systems Manager', 'Tunisia', 37, '1996-01-26');
insert into employees (name, last_name, position, office, age, start_date) values ('Joice', 'McGarrahan', 'Developer IV', 'China', 48, '1993-09-03');
insert into employees (name, last_name, position, office, age, start_date) values ('Drucie', 'Coxhell', 'Statistician IV', 'United States', 47, '1992-01-30');
insert into employees (name, last_name, position, office, age, start_date) values ('Filippa', 'Fynn', 'Assistant Media Planner', 'Brazil', 65, '2014-05-04');
insert into employees (name, last_name, position, office, age, start_date) values ('Mae', 'Wigin', 'Analyst Programmer', 'Thailand', 57, '2009-01-03');
insert into employees (name, last_name, position, office, age, start_date) values ('Samson', 'Gooder', 'Editor', 'Norway', 40, '2020-01-30');
insert into employees (name, last_name, position, office, age, start_date) values ('Courtney', 'Belle', 'Product Engineer', 'Indonesia', 34, '2018-05-09');
insert into employees (name, last_name, position, office, age, start_date) values ('Madlen', 'Giraudy', 'Nurse', 'Poland', 35, '1985-09-22');
insert into employees (name, last_name, position, office, age, start_date) values ('Dinnie', 'Skeel', 'Cost Accountant', 'France', 60, '2001-02-14');
insert into employees (name, last_name, position, office, age, start_date) values ('Huntlee', 'Worsom', 'Legal Assistant', 'China', 54, '2002-06-17');
insert into employees (name, last_name, position, office, age, start_date) values ('Jordon', 'Lowle', 'Systems Administrator IV', 'Philippines', 49, '2008-10-01');
insert into employees (name, last_name, position, office, age, start_date) values ('Benedicto', 'McCook', 'Physical Therapy Assistant', 'Poland', 46, '2016-12-10');
insert into employees (name, last_name, position, office, age, start_date) values ('Marnia', 'Tiesman', 'Biostatistician I', 'Italy', 33, '1994-11-22');
insert into employees (name, last_name, position, office, age, start_date) values ('Darsey', 'Qualtro', 'Executive Secretary', 'China', 58, '1987-07-25');
insert into employees (name, last_name, position, office, age, start_date) values ('Manda', 'Gallop', 'VP Quality Control', 'Bonaire, Saint Eustatius and Saba ', 55, '1987-07-16');
insert into employees (name, last_name, position, office, age, start_date) values ('Rebecka', 'Bredgeland', 'Recruiter', 'China', 44, '2012-09-22');
insert into employees (name, last_name, position, office, age, start_date) values ('Hashim', 'Braundt', 'Dental Hygienist', 'Chile', 39, '2001-09-06');
insert into employees (name, last_name, position, office, age, start_date) values ('Marian', 'Keuntje', 'Payment Adjustment Coordinator', 'China', 49, '2015-05-30');
insert into employees (name, last_name, position, office, age, start_date) values ('Marie-ann', 'Carrick', 'Staff Accountant IV', 'Nigeria', 55, '1994-11-01');
insert into employees (name, last_name, position, office, age, start_date) values ('Melany', 'Sandon', 'Electrical Engineer', 'Russia', 59, '2016-05-06');
insert into employees (name, last_name, position, office, age, start_date) values ('Edee', 'Finlay', 'Software Engineer I', 'Israel', 41, '2015-11-24');
insert into employees (name, last_name, position, office, age, start_date) values ('Errol', 'Oleszczak', 'Financial Advisor', 'Portugal', 38, '2017-04-03');
insert into employees (name, last_name, position, office, age, start_date) values ('Brynn', 'Skone', 'Nuclear Power Engineer', 'China', 54, '1998-03-19');
insert into employees (name, last_name, position, office, age, start_date) values ('Tabina', 'Colt', 'Media Manager I', 'China', 34, '2016-01-07');
insert into employees (name, last_name, position, office, age, start_date) values ('Verile', 'Oxlee', 'Office Assistant II', 'Ukraine', 27, '2014-11-23');
insert into employees (name, last_name, position, office, age, start_date) values ('Joletta', 'Marvel', 'VP Quality Control', 'Brazil', 60, '1999-09-16');
insert into employees (name, last_name, position, office, age, start_date) values ('Alard', 'Segebrecht', 'Staff Scientist', 'Brazil', 41, '2004-04-11');
insert into employees (name, last_name, position, office, age, start_date) values ('Maisey', 'Doy', 'Administrative Officer', 'Poland', 40, '2000-03-11');
insert into employees (name, last_name, position, office, age, start_date) values ('Cece', 'Giacomini', 'General Manager', 'France', 43, '2015-07-04');
insert into employees (name, last_name, position, office, age, start_date) values ('Cristina', 'McCathay', 'Budget/Accounting Analyst II', 'China', 43, '2018-12-06');
insert into employees (name, last_name, position, office, age, start_date) values ('Gerladina', 'Sancraft', 'Structural Analysis Engineer', 'Ecuador', 57, '2000-02-01');
insert into employees (name, last_name, position, office, age, start_date) values ('Llywellyn', 'Semark', 'Pharmacist', 'China', 58, '1994-06-25');
insert into employees (name, last_name, position, office, age, start_date) values ('Homer', 'Stayt', 'Web Designer II', 'Brazil', 59, '2018-12-20');
insert into employees (name, last_name, position, office, age, start_date) values ('Meris', 'Gofforth', 'Marketing Manager', 'Japan', 40, '2001-03-13');
insert into employees (name, last_name, position, office, age, start_date) values ('Taite', 'Curley', 'Electrical Engineer', 'Indonesia', 62, '1989-06-24');
insert into employees (name, last_name, position, office, age, start_date) values ('Courtenay', 'Perfect', 'Environmental Tech', 'Russia', 63, '2014-01-18');
insert into employees (name, last_name, position, office, age, start_date) values ('Ora', 'Johnke', 'Senior Financial Analyst', 'Bangladesh', 41, '1995-05-12');
insert into employees (name, last_name, position, office, age, start_date) values ('Alfi', 'Teal', 'Physical Therapy Assistant', 'Croatia', 40, '1995-03-08');
insert into employees (name, last_name, position, office, age, start_date) values ('Marj', 'Duff', 'Payment Adjustment Coordinator', 'Venezuela', 40, '2016-01-24');
insert into employees (name, last_name, position, office, age, start_date) values ('Tomkin', 'Coners', 'Senior Sales Associate', 'Ukraine', 51, '2020-01-27');
insert into employees (name, last_name, position, office, age, start_date) values ('Aura', 'Bostock', 'Nurse', 'Egypt', 53, '1994-12-12');
insert into employees (name, last_name, position, office, age, start_date) values ('Tonie', 'Rubinchik', 'Marketing Manager', 'Russia', 29, '1990-10-30');
insert into employees (name, last_name, position, office, age, start_date) values ('Bobbye', 'Philbrook', 'Compensation Analyst', 'South Africa', 58, '2019-07-07');
insert into employees (name, last_name, position, office, age, start_date) values ('Riva', 'Cambden', 'Sales Associate', 'United States', 50, '1989-05-21');
insert into employees (name, last_name, position, office, age, start_date) values ('Magdalene', 'Hemphill', 'Senior Cost Accountant', 'Indonesia', 26, '2007-02-14');
insert into employees (name, last_name, position, office, age, start_date) values ('Issi', 'Law', 'Research Associate', 'South Africa', 31, '2008-08-10');
insert into employees (name, last_name, position, office, age, start_date) values ('Barr', 'Bouskill', 'Junior Executive', 'Philippines', 58, '1987-01-29');
insert into employees (name, last_name, position, office, age, start_date) values ('Rouvin', 'Forlong', 'Research Associate', 'Myanmar', 38, '2004-02-11');
insert into employees (name, last_name, position, office, age, start_date) values ('Agathe', 'Blanc', 'Developer I', 'United States', 45, '2008-08-05');
insert into employees (name, last_name, position, office, age, start_date) values ('Keslie', 'Hamments', 'Marketing Assistant', 'China', 65, '2011-06-04');
insert into employees (name, last_name, position, office, age, start_date) values ('Leonard', 'MacColl', 'Electrical Engineer', 'Indonesia', 50, '2003-08-22');
insert into employees (name, last_name, position, office, age, start_date) values ('Johannes', 'Armell', 'Executive Secretary', 'China', 37, '1999-12-12');
insert into employees (name, last_name, position, office, age, start_date) values ('Ceil', 'Liles', 'Web Developer I', 'Netherlands', 43, '2006-06-25');
insert into employees (name, last_name, position, office, age, start_date) values ('Kevin', 'Sheivels', 'Human Resources Assistant IV', 'Canada', 49, '2018-06-15');
insert into employees (name, last_name, position, office, age, start_date) values ('Jessalin', 'Treadger', 'Human Resources Manager', 'China', 38, '2002-06-27');
insert into employees (name, last_name, position, office, age, start_date) values ('Munmro', 'Kainz', 'Statistician II', 'Syria', 57, '1999-07-28');
insert into employees (name, last_name, position, office, age, start_date) values ('Daryn', 'Gealy', 'Pharmacist', 'Peru', 42, '2018-03-30');
insert into employees (name, last_name, position, office, age, start_date) values ('Luke', 'Gambell', 'Programmer Analyst I', 'China', 51, '2016-10-13');
insert into employees (name, last_name, position, office, age, start_date) values ('Royal', 'Bes', 'Accountant III', 'Norfolk Island', 29, '1989-02-28');
insert into employees (name, last_name, position, office, age, start_date) values ('Flint', 'Attenborrow', 'Quality Engineer', 'Djibouti', 29, '2005-12-19');
insert into employees (name, last_name, position, office, age, start_date) values ('Belita', 'Houndson', 'Senior Sales Associate', 'Canada', 37, '2000-01-16');
insert into employees (name, last_name, position, office, age, start_date) values ('Collette', 'Bardsley', 'Electrical Engineer', 'China', 65, '2011-11-23');
insert into employees (name, last_name, position, office, age, start_date) values ('Ingram', 'Tebbitt', 'Structural Analysis Engineer', 'Poland', 47, '2005-11-17');
insert into employees (name, last_name, position, office, age, start_date) values ('Valaria', 'Sutter', 'Staff Accountant II', 'Norway', 48, '1987-11-24');
insert into employees (name, last_name, position, office, age, start_date) values ('Franny', 'Buxy', 'Help Desk Operator', 'Greece', 52, '1994-01-27');
insert into employees (name, last_name, position, office, age, start_date) values ('Hally', 'Chatband', 'Junior Executive', 'Tanzania', 62, '2008-04-03');
insert into employees (name, last_name, position, office, age, start_date) values ('Erinn', 'Itzkov', 'Electrical Engineer', 'China', 42, '2009-10-06');
insert into employees (name, last_name, position, office, age, start_date) values ('Steve', 'Ellwell', 'Marketing Assistant', 'Russia', 33, '1987-10-08');
insert into employees (name, last_name, position, office, age, start_date) values ('Madel', 'O''Lahy', 'VP Marketing', 'Thailand', 53, '2012-02-05');
insert into employees (name, last_name, position, office, age, start_date) values ('Cletus', 'Cowdrey', 'Geologist IV', 'Portugal', 53, '2010-08-21');
insert into employees (name, last_name, position, office, age, start_date) values ('Claretta', 'Trewett', 'Structural Analysis Engineer', 'Indonesia', 29, '1994-06-07');
insert into employees (name, last_name, position, office, age, start_date) values ('Kristo', 'Saffin', 'Financial Advisor', 'Indonesia', 25, '2001-08-02');
insert into employees (name, last_name, position, office, age, start_date) values ('Griffie', 'McKillop', 'Software Test Engineer II', 'Indonesia', 30, '1992-12-24');
insert into employees (name, last_name, position, office, age, start_date) values ('Elisha', 'Ferraraccio', 'General Manager', 'Greece', 34, '2003-07-15');
insert into employees (name, last_name, position, office, age, start_date) values ('Sigvard', 'Tyrwhitt', 'Executive Secretary', 'Peru', 37, '2020-05-09');
insert into employees (name, last_name, position, office, age, start_date) values ('Spence', 'Pally', 'GIS Technical Architect', 'Macedonia', 59, '2005-02-22');
insert into employees (name, last_name, position, office, age, start_date) values ('Kalila', 'McCague', 'Web Designer I', 'Argentina', 54, '2004-04-29');
insert into employees (name, last_name, position, office, age, start_date) values ('Mirna', 'Byrne', 'Dental Hygienist', 'Czech Republic', 49, '2015-08-26');
insert into employees (name, last_name, position, office, age, start_date) values ('Loree', 'Tratton', 'Staff Scientist', 'Cameroon', 51, '1991-12-09');
insert into employees (name, last_name, position, office, age, start_date) values ('Forrest', 'Gonzalvo', 'Programmer Analyst III', 'Nicaragua', 49, '1996-10-02');
insert into employees (name, last_name, position, office, age, start_date) values ('Dalton', 'Priddis', 'Paralegal', 'China', 55, '1993-10-10');
insert into employees (name, last_name, position, office, age, start_date) values ('Millicent', 'Eveling', 'Account Executive', 'China', 59, '1994-05-31');
insert into employees (name, last_name, position, office, age, start_date) values ('Dame', 'Cords', 'Occupational Therapist', 'Colombia', 29, '2002-07-21');
insert into employees (name, last_name, position, office, age, start_date) values ('Margalit', 'Parkin', 'Accounting Assistant I', 'Indonesia', 28, '2010-06-18');
insert into employees (name, last_name, position, office, age, start_date) values ('Mignonne', 'Brogiotti', 'VP Product Management', 'Gabon', 64, '2015-11-29');
insert into employees (name, last_name, position, office, age, start_date) values ('Iorgo', 'O''Loughane', 'Engineer I', 'Portugal', 45, '1992-11-01');
insert into employees (name, last_name, position, office, age, start_date) values ('Jabez', 'Handrek', 'Tax Accountant', 'Palestinian Territory', 31, '2012-09-18');
insert into employees (name, last_name, position, office, age, start_date) values ('Josephine', 'Braikenridge', 'Account Coordinator', 'Philippines', 39, '1990-03-04');
insert into employees (name, last_name, position, office, age, start_date) values ('Torrey', 'Colliar', 'VP Product Management', 'Portugal', 61, '2012-07-28');
insert into employees (name, last_name, position, office, age, start_date) values ('Breanne', 'Shilladay', 'Speech Pathologist', 'Czech Republic', 48, '2014-01-21');
insert into employees (name, last_name, position, office, age, start_date) values ('Sterne', 'Samson', 'Senior Financial Analyst', 'Russia', 26, '1997-07-12');
insert into employees (name, last_name, position, office, age, start_date) values ('Delmor', 'Paulack', 'Editor', 'United States', 38, '2000-05-10');
insert into employees (name, last_name, position, office, age, start_date) values ('Meier', 'Boscher', 'Product Engineer', 'Portugal', 48, '2004-11-17');
insert into employees (name, last_name, position, office, age, start_date) values ('Leeann', 'Rodnight', 'Human Resources Manager', 'Russia', 43, '1994-04-12');
insert into employees (name, last_name, position, office, age, start_date) values ('Cameron', 'MacFadzean', 'Software Test Engineer III', 'Mexico', 65, '2019-11-01');
insert into employees (name, last_name, position, office, age, start_date) values ('Olenolin', 'Allsep', 'Staff Accountant II', 'Yemen', 63, '1996-09-12');
insert into employees (name, last_name, position, office, age, start_date) values ('Starr', 'Lansbury', 'Administrative Officer', 'Serbia', 55, '1998-02-27');
insert into employees (name, last_name, position, office, age, start_date) values ('Brandea', 'Merchant', 'Human Resources Manager', 'Haiti', 34, '2007-06-28');
insert into employees (name, last_name, position, office, age, start_date) values ('Johnathon', 'Merryman', 'Professor', 'Portugal', 60, '1995-10-12');
insert into employees (name, last_name, position, office, age, start_date) values ('Brose', 'Gori', 'Clinical Specialist', 'Indonesia', 64, '1991-03-09');
insert into employees (name, last_name, position, office, age, start_date) values ('Nigel', 'Costley', 'Programmer IV', 'Madagascar', 44, '1993-08-05');
insert into employees (name, last_name, position, office, age, start_date) values ('Phoebe', 'Napoleon', 'Senior Editor', 'Ukraine', 25, '1996-11-19');
insert into employees (name, last_name, position, office, age, start_date) values ('Alyosha', 'Madge', 'Web Designer IV', 'Indonesia', 48, '1991-06-10');
insert into employees (name, last_name, position, office, age, start_date) values ('Tiffie', 'Knighton', 'Mechanical Systems Engineer', 'Germany', 63, '2004-06-01');
insert into employees (name, last_name, position, office, age, start_date) values ('Sharlene', 'Menzies', 'Assistant Media Planner', 'Zambia', 48, '1989-12-10');
insert into employees (name, last_name, position, office, age, start_date) values ('Abbott', 'Peters', 'Product Engineer', 'Argentina', 27, '1998-10-20');
insert into employees (name, last_name, position, office, age, start_date) values ('Emery', 'Nesterov', 'Legal Assistant', 'Brazil', 52, '1992-02-21');
insert into employees (name, last_name, position, office, age, start_date) values ('Daron', 'Oddboy', 'Nuclear Power Engineer', 'China', 34, '2019-03-24');
insert into employees (name, last_name, position, office, age, start_date) values ('Silvana', 'Burditt', 'Account Executive', 'China', 38, '2009-12-01');
insert into employees (name, last_name, position, office, age, start_date) values ('Samson', 'Pickerin', 'Pharmacist', 'Japan', 40, '2013-02-04');
insert into employees (name, last_name, position, office, age, start_date) values ('Farleigh', 'Featherstone', 'Quality Control Specialist', 'Mongolia', 65, '2004-10-02');
insert into employees (name, last_name, position, office, age, start_date) values ('Madella', 'Jessop', 'Pharmacist', 'China', 58, '2014-06-07');
insert into employees (name, last_name, position, office, age, start_date) values ('Lilyan', 'Bestwick', 'Assistant Professor', 'China', 40, '2008-01-28');
insert into employees (name, last_name, position, office, age, start_date) values ('Adolphe', 'Dunbobbin', 'Data Coordiator', 'Portugal', 40, '1985-11-13');
insert into employees (name, last_name, position, office, age, start_date) values ('Lorant', 'Owbridge', 'Computer Systems Analyst I', 'United States', 30, '2004-05-28');
insert into employees (name, last_name, position, office, age, start_date) values ('Alwyn', 'Medgwick', 'Office Assistant I', 'Indonesia', 36, '2009-04-12');
insert into employees (name, last_name, position, office, age, start_date) values ('Mollee', 'MacDonell', 'Dental Hygienist', 'Philippines', 62, '2010-02-24');
insert into employees (name, last_name, position, office, age, start_date) values ('Leigh', 'Mc Elory', 'Sales Representative', 'Indonesia', 49, '1998-10-08');
insert into employees (name, last_name, position, office, age, start_date) values ('Juliet', 'Eaves', 'Assistant Professor', 'China', 57, '1999-03-23');
insert into employees (name, last_name, position, office, age, start_date) values ('Arnie', 'Peek', 'Help Desk Operator', 'Russia', 64, '1995-10-18');
insert into employees (name, last_name, position, office, age, start_date) values ('Chelsie', 'Feldberger', 'Geological Engineer', 'Finland', 64, '2001-04-29');
insert into employees (name, last_name, position, office, age, start_date) values ('Flora', 'Wasmer', 'Desktop Support Technician', 'China', 48, '2006-12-27');
insert into employees (name, last_name, position, office, age, start_date) values ('Malory', 'Risby', 'VP Accounting', 'Indonesia', 50, '2013-03-12');
insert into employees (name, last_name, position, office, age, start_date) values ('Chere', 'Worrell', 'Nurse', 'Indonesia', 44, '2013-03-17');
insert into employees (name, last_name, position, office, age, start_date) values ('Alfie', 'Rottger', 'Research Assistant II', 'China', 63, '2006-09-10');
insert into employees (name, last_name, position, office, age, start_date) values ('Marie-ann', 'Cocker', 'Executive Secretary', 'Philippines', 26, '1998-01-10');
insert into employees (name, last_name, position, office, age, start_date) values ('Loise', 'Cecely', 'VP Marketing', 'Ukraine', 35, '1993-07-23');
insert into employees (name, last_name, position, office, age, start_date) values ('Florette', 'Hamer', 'Professor', 'Indonesia', 44, '2010-03-26');
insert into employees (name, last_name, position, office, age, start_date) values ('Pearline', 'Aucock', 'Director of Sales', 'Russia', 48, '2008-04-10');
insert into employees (name, last_name, position, office, age, start_date) values ('Christean', 'Walbridge', 'Structural Engineer', 'Estonia', 29, '1996-07-26');
insert into employees (name, last_name, position, office, age, start_date) values ('Salvador', 'Adnams', 'Assistant Professor', 'Indonesia', 64, '1995-02-14');
insert into employees (name, last_name, position, office, age, start_date) values ('Florie', 'Jarratt', 'VP Sales', 'Brazil', 28, '1986-02-06');
insert into employees (name, last_name, position, office, age, start_date) values ('Lettie', 'Simoneschi', 'Web Developer II', 'Sweden', 60, '2012-12-15');
insert into employees (name, last_name, position, office, age, start_date) values ('Gwenneth', 'Gaish', 'Product Engineer', 'Indonesia', 55, '1985-10-30');
insert into employees (name, last_name, position, office, age, start_date) values ('Alden', 'Lambertini', 'Dental Hygienist', 'United States', 58, '2001-03-21');
insert into employees (name, last_name, position, office, age, start_date) values ('Burt', 'Langhor', 'Food Chemist', 'Philippines', 32, '2018-11-13');
insert into employees (name, last_name, position, office, age, start_date) values ('Brandy', 'Coucha', 'Professor', 'Ivory Coast', 43, '2009-08-14');
insert into employees (name, last_name, position, office, age, start_date) values ('Tyrone', 'MacRorie', 'Registered Nurse', 'Greece', 36, '2016-05-20');
insert into employees (name, last_name, position, office, age, start_date) values ('Murdoch', 'Lewens', 'Media Manager I', 'Bosnia and Herzegovina', 38, '2018-04-28');
insert into employees (name, last_name, position, office, age, start_date) values ('Christoffer', 'Smitheman', 'Design Engineer', 'Reunion', 44, '1991-07-13');
insert into employees (name, last_name, position, office, age, start_date) values ('Heath', 'Harpham', 'Research Associate', 'Brazil', 53, '2003-03-28');
insert into employees (name, last_name, position, office, age, start_date) values ('Patricia', 'Limbourne', 'Engineer I', 'South Africa', 38, '1996-10-15');
insert into employees (name, last_name, position, office, age, start_date) values ('Wallis', 'Fooks', 'Research Associate', 'Indonesia', 27, '2001-08-29');
insert into employees (name, last_name, position, office, age, start_date) values ('Delinda', 'Meikle', 'Accountant III', 'France', 33, '2001-12-22');
insert into employees (name, last_name, position, office, age, start_date) values ('Linn', 'Penzer', 'Staff Scientist', 'Poland', 62, '1995-11-01');
insert into employees (name, last_name, position, office, age, start_date) values ('Mortimer', 'Middis', 'Editor', 'Panama', 29, '1989-07-12');
insert into employees (name, last_name, position, office, age, start_date) values ('Buck', 'Ferrarin', 'Research Associate', 'Russia', 63, '2013-06-06');
insert into employees (name, last_name, position, office, age, start_date) values ('Bibi', 'Chritchlow', 'Biostatistician IV', 'Sweden', 35, '1990-05-21');
insert into employees (name, last_name, position, office, age, start_date) values ('Morty', 'Galego', 'Research Associate', 'Botswana', 55, '1990-04-22');
insert into employees (name, last_name, position, office, age, start_date) values ('Moyra', 'Twining', 'Accountant I', 'Nigeria', 63, '1999-02-22');
insert into employees (name, last_name, position, office, age, start_date) values ('Adrien', 'Orrett', 'Software Test Engineer II', 'Philippines', 65, '1987-12-15');
insert into employees (name, last_name, position, office, age, start_date) values ('Fredericka', 'Ingles', 'Research Nurse', 'France', 51, '1996-12-29');
insert into employees (name, last_name, position, office, age, start_date) values ('Rhody', 'Fenimore', 'Accountant III', 'Mexico', 31, '2016-06-29');
insert into employees (name, last_name, position, office, age, start_date) values ('Erek', 'Threadgold', 'Civil Engineer', 'Indonesia', 34, '2002-07-19');
insert into employees (name, last_name, position, office, age, start_date) values ('Walker', 'Keaton', 'Accountant I', 'Portugal', 58, '1988-07-04');
insert into employees (name, last_name, position, office, age, start_date) values ('Ichabod', 'Hollow', 'Technical Writer', 'China', 37, '1994-02-07');
insert into employees (name, last_name, position, office, age, start_date) values ('Emmit', 'Oakeshott', 'Analog Circuit Design manager', 'Egypt', 43, '1997-12-22');
insert into employees (name, last_name, position, office, age, start_date) values ('Holt', 'Garmanson', 'Assistant Manager', 'Philippines', 27, '1992-04-19');
insert into employees (name, last_name, position, office, age, start_date) values ('Sutherland', 'Margaret', 'Desktop Support Technician', 'Portugal', 51, '2016-05-10');
insert into employees (name, last_name, position, office, age, start_date) values ('Vida', 'Tiplady', 'Director of Sales', 'Russia', 29, '1999-02-24');
insert into employees (name, last_name, position, office, age, start_date) values ('Charissa', 'Comizzoli', 'Associate Professor', 'China', 51, '2010-09-16');
insert into employees (name, last_name, position, office, age, start_date) values ('Penelopa', 'de Vaen', 'Structural Analysis Engineer', 'Indonesia', 36, '2003-03-20');
insert into employees (name, last_name, position, office, age, start_date) values ('Verene', 'Schurcke', 'Staff Scientist', 'Indonesia', 47, '2006-11-08');
insert into employees (name, last_name, position, office, age, start_date) values ('Byram', 'Borgesio', 'Account Executive', 'Latvia', 60, '1986-12-23');
insert into employees (name, last_name, position, office, age, start_date) values ('Reginauld', 'Domm', 'Director of Sales', 'Philippines', 60, '1998-02-18');
insert into employees (name, last_name, position, office, age, start_date) values ('Meta', 'Grasha', 'Geological Engineer', 'Mongolia', 53, '2005-09-06');
insert into employees (name, last_name, position, office, age, start_date) values ('Frazer', 'Rafe', 'Design Engineer', 'Ukraine', 25, '2014-02-01');
insert into employees (name, last_name, position, office, age, start_date) values ('Garnet', 'Edwin', 'Project Manager', 'China', 46, '2007-06-29');
insert into employees (name, last_name, position, office, age, start_date) values ('Leora', 'Vanner', 'Structural Analysis Engineer', 'Russia', 61, '1990-09-13');
insert into employees (name, last_name, position, office, age, start_date) values ('Wendeline', 'Kenrat', 'Compensation Analyst', 'Haiti', 44, '2014-07-19');
insert into employees (name, last_name, position, office, age, start_date) values ('Dominique', 'Hardman', 'Software Engineer III', 'Indonesia', 54, '1996-06-10');
insert into employees (name, last_name, position, office, age, start_date) values ('Tremain', 'Barnhill', 'Budget/Accounting Analyst III', 'Russia', 65, '1993-10-29');
insert into employees (name, last_name, position, office, age, start_date) values ('Zelig', 'Cavilla', 'Programmer Analyst I', 'Indonesia', 65, '2010-10-10');
insert into employees (name, last_name, position, office, age, start_date) values ('Stepha', 'Tregiddo', 'Editor', 'Indonesia', 37, '2015-08-28');
insert into employees (name, last_name, position, office, age, start_date) values ('Florri', 'Lockton', 'Senior Financial Analyst', 'Ecuador', 39, '2001-03-25');
insert into employees (name, last_name, position, office, age, start_date) values ('Gwenore', 'Lethby', 'Teacher', 'China', 28, '1987-10-27');
insert into employees (name, last_name, position, office, age, start_date) values ('Charlotta', 'Weston', 'Senior Financial Analyst', 'Bulgaria', 58, '2011-11-19');
insert into employees (name, last_name, position, office, age, start_date) values ('Enrico', 'Verchambre', 'VP Accounting', 'Indonesia', 29, '1988-02-11');
insert into employees (name, last_name, position, office, age, start_date) values ('Padriac', 'Raycroft', 'Assistant Media Planner', 'Philippines', 52, '1986-09-02');
insert into employees (name, last_name, position, office, age, start_date) values ('Andra', 'Heskey', 'Account Coordinator', 'China', 39, '2014-07-14');
insert into employees (name, last_name, position, office, age, start_date) values ('Jaquelin', 'Salliere', 'Structural Analysis Engineer', 'Philippines', 64, '1995-03-14');
insert into employees (name, last_name, position, office, age, start_date) values ('Tobie', 'Tiddy', 'Recruiting Manager', 'Bosnia and Herzegovina', 55, '1985-09-18');
insert into employees (name, last_name, position, office, age, start_date) values ('Lion', 'Bubear', 'Web Developer I', 'United States', 45, '2018-05-21');
insert into employees (name, last_name, position, office, age, start_date) values ('Timmy', 'Showt', 'Data Coordiator', 'Thailand', 59, '2004-03-18');
insert into employees (name, last_name, position, office, age, start_date) values ('Nancee', 'Bodesson', 'Data Coordiator', 'Philippines', 25, '2001-07-14');
insert into employees (name, last_name, position, office, age, start_date) values ('Ilyssa', 'Bras', 'Analyst Programmer', 'Russia', 55, '2003-05-13');
insert into employees (name, last_name, position, office, age, start_date) values ('Enos', 'Cawthery', 'VP Marketing', 'China', 33, '2007-05-26');
insert into employees (name, last_name, position, office, age, start_date) values ('Caritta', 'Nesfield', 'Automation Specialist IV', 'Indonesia', 36, '1994-09-04');
insert into employees (name, last_name, position, office, age, start_date) values ('Rolph', 'Botham', 'Health Coach I', 'Portugal', 63, '1987-05-21');
insert into employees (name, last_name, position, office, age, start_date) values ('Andi', 'Langabeer', 'Junior Executive', 'Gabon', 27, '1991-07-19');
insert into employees (name, last_name, position, office, age, start_date) values ('Dennie', 'Stapford', 'Senior Financial Analyst', 'China', 43, '2008-10-05');
insert into employees (name, last_name, position, office, age, start_date) values ('Bill', 'Kermott', 'Tax Accountant', 'Canada', 27, '1986-11-25');
insert into employees (name, last_name, position, office, age, start_date) values ('Cheston', 'Dolder', 'Account Representative I', 'Philippines', 48, '2017-07-26');
insert into employees (name, last_name, position, office, age, start_date) values ('Ignacius', 'Woodrough', 'Analyst Programmer', 'Indonesia', 31, '2007-06-13');
insert into employees (name, last_name, position, office, age, start_date) values ('Ozzy', 'Dugmore', 'Account Executive', 'Japan', 56, '1995-10-13');
insert into employees (name, last_name, position, office, age, start_date) values ('Nat', 'Beere', 'Professor', 'China', 57, '1985-10-07');
insert into employees (name, last_name, position, office, age, start_date) values ('Scott', 'O''Dwyer', 'Accounting Assistant III', 'Indonesia', 56, '2000-09-23');
insert into employees (name, last_name, position, office, age, start_date) values ('Wolfgang', 'Gaymar', 'Engineer I', 'Russia', 49, '1995-07-01');
insert into employees (name, last_name, position, office, age, start_date) values ('Evan', 'Wogdon', 'Staff Accountant I', 'China', 54, '2007-10-14');
insert into employees (name, last_name, position, office, age, start_date) values ('Olia', 'Christofle', 'Accountant I', 'China', 45, '2001-03-15');
insert into employees (name, last_name, position, office, age, start_date) values ('Alayne', 'Lepere', 'Quality Engineer', 'Brazil', 28, '1992-02-25');
insert into employees (name, last_name, position, office, age, start_date) values ('Sara', 'Trowsdale', 'Administrative Officer', 'Ukraine', 31, '1991-06-19');
insert into employees (name, last_name, position, office, age, start_date) values ('Alisun', 'Mateuszczyk', 'Registered Nurse', 'Czech Republic', 49, '1995-10-10');
insert into employees (name, last_name, position, office, age, start_date) values ('Leighton', 'McGahern', 'Legal Assistant', 'France', 39, '1996-11-25');
insert into employees (name, last_name, position, office, age, start_date) values ('Aloise', 'McRobbie', 'Structural Engineer', 'Japan', 44, '1999-04-10');
insert into employees (name, last_name, position, office, age, start_date) values ('Dag', 'Blatcher', 'Developer III', 'Russia', 29, '2020-08-13');
insert into employees (name, last_name, position, office, age, start_date) values ('Mathian', 'Heustice', 'Chemical Engineer', 'Serbia', 30, '2020-05-02');
insert into employees (name, last_name, position, office, age, start_date) values ('Effie', 'Necrews', 'Research Assistant II', 'Indonesia', 42, '2000-08-06');
insert into employees (name, last_name, position, office, age, start_date) values ('Adelind', 'Merry', 'Staff Accountant III', 'Japan', 40, '1989-04-21');
insert into employees (name, last_name, position, office, age, start_date) values ('Janaye', 'Loffel', 'Senior Sales Associate', 'Iran', 35, '2018-01-19');
insert into employees (name, last_name, position, office, age, start_date) values ('Berrie', 'Ranking', 'Administrative Officer', 'Honduras', 53, '2000-09-03');
insert into employees (name, last_name, position, office, age, start_date) values ('Kyla', 'McClintock', 'Occupational Therapist', 'United States', 56, '2015-09-03');
insert into employees (name, last_name, position, office, age, start_date) values ('Solly', 'Sotheron', 'Biostatistician I', 'Russia', 55, '1997-07-25');
insert into employees (name, last_name, position, office, age, start_date) values ('Bernardo', 'Lanfare', 'Sales Associate', 'Thailand', 28, '1988-08-19');
insert into employees (name, last_name, position, office, age, start_date) values ('Nedda', 'Pendlebury', 'Payment Adjustment Coordinator', 'Czech Republic', 65, '2018-02-02');
insert into employees (name, last_name, position, office, age, start_date) values ('Pet', 'Fancet', 'Compensation Analyst', 'Greece', 25, '2018-07-27');
insert into employees (name, last_name, position, office, age, start_date) values ('Trstram', 'Estick', 'Director of Sales', 'Indonesia', 47, '2003-05-26');
insert into employees (name, last_name, position, office, age, start_date) values ('Brigham', 'Hiddy', 'Physical Therapy Assistant', 'China', 59, '2020-01-10');
insert into employees (name, last_name, position, office, age, start_date) values ('Helenelizabeth', 'Cleynaert', 'Internal Auditor', 'Greece', 43, '2005-03-17');
insert into employees (name, last_name, position, office, age, start_date) values ('Darrin', 'Coggan', 'Executive Secretary', 'Morocco', 42, '2005-03-27');
insert into employees (name, last_name, position, office, age, start_date) values ('Gratiana', 'Simak', 'Budget/Accounting Analyst I', 'China', 56, '2004-02-29');
insert into employees (name, last_name, position, office, age, start_date) values ('Welch', 'Wisson', 'Financial Advisor', 'China', 44, '1997-11-27');
insert into employees (name, last_name, position, office, age, start_date) values ('Ariel', 'Fuzzard', 'Nuclear Power Engineer', 'China', 42, '2009-05-25');
insert into employees (name, last_name, position, office, age, start_date) values ('Lizette', 'Dand', 'Staff Scientist', 'Sweden', 25, '2005-10-05');
insert into employees (name, last_name, position, office, age, start_date) values ('Bethena', 'Fridd', 'Nurse', 'Greece', 47, '2012-05-16');
insert into employees (name, last_name, position, office, age, start_date) values ('Hildy', 'Frill', 'Office Assistant I', 'Ireland', 45, '2012-12-19');
insert into employees (name, last_name, position, office, age, start_date) values ('Marybeth', 'Archibold', 'Programmer Analyst IV', 'Portugal', 58, '2020-01-19');
insert into employees (name, last_name, position, office, age, start_date) values ('Shirlee', 'Girardet', 'Recruiting Manager', 'Portugal', 31, '2016-05-15');
insert into employees (name, last_name, position, office, age, start_date) values ('Earl', 'Blyth', 'Statistician I', 'Netherlands', 41, '2005-07-18');
insert into employees (name, last_name, position, office, age, start_date) values ('Alfy', 'Esposita', 'Software Test Engineer I', 'Indonesia', 35, '2018-07-28');
insert into employees (name, last_name, position, office, age, start_date) values ('Peggie', 'Dufaire', 'Recruiting Manager', 'China', 56, '2001-09-07');
insert into employees (name, last_name, position, office, age, start_date) values ('Cassius', 'Borrott', 'Speech Pathologist', 'China', 50, '2014-04-01');
insert into employees (name, last_name, position, office, age, start_date) values ('Olivier', 'Trythall', 'Research Assistant III', 'Philippines', 62, '2002-11-14');
insert into employees (name, last_name, position, office, age, start_date) values ('Carolus', 'Ephgrave', 'Director of Sales', 'Argentina', 26, '2000-11-06');
insert into employees (name, last_name, position, office, age, start_date) values ('Maryrose', 'Shawcross', 'Help Desk Operator', 'China', 64, '2004-07-07');
insert into employees (name, last_name, position, office, age, start_date) values ('Ferdinanda', 'Blade', 'Account Representative IV', 'Montenegro', 33, '1987-09-15');
insert into employees (name, last_name, position, office, age, start_date) values ('Philbert', 'Dain', 'Research Associate', 'Syria', 30, '2000-03-23');
insert into employees (name, last_name, position, office, age, start_date) values ('Washington', 'Rosenschein', 'Web Designer I', 'Indonesia', 33, '2002-05-16');
insert into employees (name, last_name, position, office, age, start_date) values ('Hamel', 'Elmore', 'Biostatistician I', 'Azerbaijan', 60, '2008-12-13');
insert into employees (name, last_name, position, office, age, start_date) values ('Felita', 'Renzo', 'Office Assistant I', 'Iraq', 27, '1999-06-26');
insert into employees (name, last_name, position, office, age, start_date) values ('Michaela', 'Luesley', 'Physical Therapy Assistant', 'Thailand', 52, '1986-04-01');
insert into employees (name, last_name, position, office, age, start_date) values ('Madella', 'Millom', 'Software Engineer I', 'Indonesia', 31, '1987-11-16');