import { builddatatable } from './pagination_modules/buildDataTable.js'

const data = [
    {
      "id": "1",
      "first_name": "Sidoney",
      "last_name": "Josebury",
      "address": "00038 Nelson Street",
      "city": "Shadui",
      "phone": "688-737-8227",
      "email": "sjosebury0@utexas.edu",
      "company_name": "Rhybox",
      "position": "Chief Design Engineer",
      "office": "China",
      "age": "31",
      "start_date": "1992-08-05"
    },
    {
      "id": "2",
      "first_name": "Stanley",
      "last_name": "Crosseland",
      "address": "900 Killdeer Street",
      "city": "Antas",
      "phone": "174-120-4839",
      "email": "scrosseland1@economist.com",
      "company_name": "Cogidoo",
      "position": "Recruiting Manager",
      "office": "Portugal",
      "age": "47",
      "start_date": "1993-07-28"
    },
    {
      "id": "3",
      "first_name": "Early",
      "last_name": "Hartell",
      "address": "08 Hollow Ridge Drive",
      "city": "Minsk",
      "phone": "261-731-1966",
      "email": "ehartell2@stumbleupon.com",
      "company_name": "Jabberbean",
      "position": "Accounting Assistant IV",
      "office": "Belarus",
      "age": "32",
      "start_date": "2000-04-06"
    },
    {
      "id": "4",
      "first_name": "Reilly",
      "last_name": "McComiskie",
      "address": "869 Buena Vista Place",
      "city": "Banjarjo",
      "phone": "816-196-5984",
      "email": "rmccomiskie3@tripod.com",
      "company_name": "Feedspan",
      "position": "Statistician II",
      "office": "Indonesia",
      "age": "55",
      "start_date": "1986-03-14"
    },
    {
      "id": "5",
      "first_name": "Aundrea",
      "last_name": "Dewsnap",
      "address": "172 Stephen Court",
      "city": "Faaone",
      "phone": "507-455-4484",
      "email": "adewsnap4@hugedomains.com",
      "company_name": "Shuffletag",
      "position": "Data Coordiator",
      "office": "French Polynesia",
      "age": "38",
      "start_date": "2007-06-20"
    },
    {
      "id": "6",
      "first_name": "Shel",
      "last_name": "Agneau",
      "address": "009 Forest Dale Center",
      "city": "Atães",
      "phone": "427-380-5195",
      "email": "sagneau5@noaa.gov",
      "company_name": "Vimbo",
      "position": "Payment Adjustment Coordinator",
      "office": "Portugal",
      "age": "34",
      "start_date": "2006-01-16"
    },
    {
      "id": "7",
      "first_name": "Patrizio",
      "last_name": "Grinval",
      "address": "24 Lerdahl Lane",
      "city": "Sydney",
      "phone": "873-984-0481",
      "email": "pgrinval6@cbslocal.com",
      "company_name": "Browseblab",
      "position": "Marketing Manager",
      "office": "Australia",
      "age": "27",
      "start_date": "2017-04-22"
    },
    {
      "id": "8",
      "first_name": "Maxie",
      "last_name": "Robbins",
      "address": "0108 Sommers Junction",
      "city": "Sentul",
      "phone": "785-994-7156",
      "email": "mrobbins7@theglobeandmail.com",
      "company_name": "Rhycero",
      "position": "Product Engineer",
      "office": "Indonesia",
      "age": "27",
      "start_date": "1998-08-04"
    },
    {
      "id": "9",
      "first_name": "Broddy",
      "last_name": "Brookshaw",
      "address": "7733 Walton Crossing",
      "city": "Anniston",
      "phone": "256-866-9524",
      "email": "bbrookshaw8@homestead.com",
      "company_name": "Leenti",
      "position": "Senior Developer",
      "office": "United States",
      "age": "47",
      "start_date": "2001-09-28"
    },
    {
      "id": "10",
      "first_name": "Kristofor",
      "last_name": "Marcone",
      "address": "016 Esker Point",
      "city": "Negoslavci",
      "phone": "517-562-4372",
      "email": "kmarcone9@wunderground.com",
      "company_name": "Tanoodle",
      "position": "Human Resources Manager",
      "office": "Croatia",
      "age": "45",
      "start_date": "1997-07-27"
    },
    {
      "id": "11",
      "first_name": "Templeton",
      "last_name": "Grafton",
      "address": "5 Oriole Lane",
      "city": "Rychwał",
      "phone": "223-446-7359",
      "email": "tgraftona@businessinsider.com",
      "company_name": "Rhybox",
      "position": "Dental Hygienist",
      "office": "Poland",
      "age": "56",
      "start_date": "1985-09-02"
    },
    {
      "id": "12",
      "first_name": "Waylan",
      "last_name": "Lowndsborough",
      "address": "053 Blaine Circle",
      "city": "Dibba Al-Hisn",
      "phone": "997-213-5383",
      "email": "wlowndsboroughb@miibeian.gov.cn",
      "company_name": "Youspan",
      "position": "GIS Technical Architect",
      "office": "United Arab Emirates",
      "age": "62",
      "start_date": "2000-12-24"
    },
    {
      "id": "13",
      "first_name": "Kristin",
      "last_name": "Cunningham",
      "address": "88 Banding Lane",
      "city": "Adigeni",
      "phone": "290-401-9584",
      "email": "kcunninghamc@dropbox.com",
      "company_name": "Yombu",
      "position": "Information Systems Manager",
      "office": "Georgia",
      "age": "54",
      "start_date": "2019-07-25"
    },
    {
      "id": "14",
      "first_name": "Meade",
      "last_name": "Stranaghan",
      "address": "008 Manufacturers Drive",
      "city": "Bayrachky",
      "phone": "482-375-9654",
      "email": "mstranaghand@geocities.com",
      "company_name": "Agimba",
      "position": "Civil Engineer",
      "office": "Ukraine",
      "age": "52",
      "start_date": "1990-08-27"
    },
    {
      "id": "15",
      "first_name": "Travis",
      "last_name": "Van der Merwe",
      "address": "5123 Trailsway Hill",
      "city": "Yevpatoriya",
      "phone": "659-517-5080",
      "email": "tvandermerwee@businessinsider.com",
      "company_name": "Agimba",
      "position": "Human Resources Manager",
      "office": "Ukraine",
      "age": "62",
      "start_date": "1994-12-03"
    },
    {
      "id": "16",
      "first_name": "Orlan",
      "last_name": "Keetley",
      "address": "9375 Northridge Pass",
      "city": "Mougins",
      "phone": "942-923-3885",
      "email": "okeetleyf@mashable.com",
      "company_name": "Twimm",
      "position": "General Manager",
      "office": "France",
      "age": "38",
      "start_date": "2017-08-28"
    },
    {
      "id": "17",
      "first_name": "Gayleen",
      "last_name": "Harriagn",
      "address": "201 Roxbury Pass",
      "city": "Sukojember",
      "phone": "413-534-3320",
      "email": "gharriagng@blog.com",
      "company_name": "Nlounge",
      "position": "Dental Hygienist",
      "office": "Indonesia",
      "age": "29",
      "start_date": "2019-03-06"
    },
    {
      "id": "18",
      "first_name": "Filberte",
      "last_name": "Penniell",
      "address": "77674 Commercial Plaza",
      "city": "Skála Oropoú",
      "phone": "748-496-8525",
      "email": "fpenniellh@topsy.com",
      "company_name": "Yodel",
      "position": "Human Resources Manager",
      "office": "Greece",
      "age": "61",
      "start_date": "1990-10-07"
    },
    {
      "id": "19",
      "first_name": "Ronnie",
      "last_name": "Mantz",
      "address": "5006 Londonderry Junction",
      "city": "Sundbyberg",
      "phone": "566-263-7324",
      "email": "rmantzi@independent.co.uk",
      "company_name": "Roomm",
      "position": "Account Coordinator",
      "office": "Sweden",
      "age": "38",
      "start_date": "2019-11-23"
    },
    {
      "id": "20",
      "first_name": "Blakeley",
      "last_name": "Ohanessian",
      "address": "87 David Junction",
      "city": "les Escaldes",
      "phone": "859-721-4630",
      "email": "bohanessianj@elpais.com",
      "company_name": "Buzzbean",
      "position": "Product Engineer",
      "office": "Andorra",
      "age": "65",
      "start_date": "1995-10-16"
    },
    {
      "id": "21",
      "first_name": "Flory",
      "last_name": "Treweek",
      "address": "164 Eastlawn Park",
      "city": "Cerro Corá",
      "phone": "420-908-1573",
      "email": "ftreweekk@hao123.com",
      "company_name": "Youtags",
      "position": "VP Marketing",
      "office": "Argentina",
      "age": "62",
      "start_date": "2008-12-20"
    },
    {
      "id": "22",
      "first_name": "Toinette",
      "last_name": "Matthai",
      "address": "14504 Manley Center",
      "city": "Yara",
      "phone": "120-683-8813",
      "email": "tmatthail@youtu.be",
      "company_name": "Kwinu",
      "position": "Administrative Officer",
      "office": "Cuba",
      "age": "54",
      "start_date": "1989-06-07"
    },
    {
      "id": "23",
      "first_name": "Emlyn",
      "last_name": "Jewitt",
      "address": "51255 Sage Junction",
      "city": "Drachten",
      "phone": "683-824-7951",
      "email": "ejewittm@hatena.ne.jp",
      "company_name": "Thoughtbeat",
      "position": "Computer Systems Analyst II",
      "office": "Netherlands",
      "age": "64",
      "start_date": "2003-09-11"
    },
    {
      "id": "24",
      "first_name": "Alfie",
      "last_name": "Roark",
      "address": "933 Charing Cross Plaza",
      "city": "Gaotan",
      "phone": "471-491-2460",
      "email": "aroarkn@shop-pro.jp",
      "company_name": "Youfeed",
      "position": "Accounting Assistant III",
      "office": "China",
      "age": "64",
      "start_date": "1995-12-10"
    },
    {
      "id": "25",
      "first_name": "Ernst",
      "last_name": "Woodfin",
      "address": "1011 Oak Junction",
      "city": "Edsbyn",
      "phone": "119-635-0917",
      "email": "ewoodfino@is.gd",
      "company_name": "Dabshots",
      "position": "Help Desk Technician",
      "office": "Sweden",
      "age": "41",
      "start_date": "1987-10-22"
    },
    {
      "id": "26",
      "first_name": "Maisey",
      "last_name": "Doughartie",
      "address": "1891 Esch Street",
      "city": "Tsibulev",
      "phone": "271-871-0685",
      "email": "mdoughartiep@hatena.ne.jp",
      "company_name": "Skyvu",
      "position": "Nuclear Power Engineer",
      "office": "Ukraine",
      "age": "36",
      "start_date": "2004-06-01"
    },
    {
      "id": "27",
      "first_name": "Rachael",
      "last_name": "Lidbetter",
      "address": "83103 Leroy Terrace",
      "city": "Santa Cruz",
      "phone": "915-735-5088",
      "email": "rlidbetterq@ehow.com",
      "company_name": "Yoveo",
      "position": "Recruiting Manager",
      "office": "Mexico",
      "age": "41",
      "start_date": "2016-05-24"
    },
    {
      "id": "28",
      "first_name": "Madalena",
      "last_name": "Wannes",
      "address": "9919 Fordem Trail",
      "city": "San Rafael",
      "phone": "861-790-5362",
      "email": "mwannesr@netscape.com",
      "company_name": "Youbridge",
      "position": "Pharmacist",
      "office": "Philippines",
      "age": "33",
      "start_date": "1997-07-15"
    },
    {
      "id": "29",
      "first_name": "Graig",
      "last_name": "Wardle",
      "address": "79 American Ash Lane",
      "city": "Pandangan Kulon",
      "phone": "149-315-2901",
      "email": "gwardles@ted.com",
      "company_name": "Pixonyx",
      "position": "Programmer Analyst III",
      "office": "Indonesia",
      "age": "27",
      "start_date": "2003-05-03"
    },
    {
      "id": "30",
      "first_name": "Hans",
      "last_name": "Spurdens",
      "address": "4299 Lillian Point",
      "city": "Barão de Melgaço",
      "phone": "398-281-1272",
      "email": "hspurdenst@drupal.org",
      "company_name": "Teklist",
      "position": "Budget/Accounting Analyst I",
      "office": "Brazil",
      "age": "51",
      "start_date": "1987-06-09"
    },
    {
      "id": "31",
      "first_name": "Emilio",
      "last_name": "Gilhool",
      "address": "40 Autumn Leaf Court",
      "city": "Purwodadi",
      "phone": "415-805-6302",
      "email": "egilhoolu@un.org",
      "company_name": "Flashset",
      "position": "Media Manager IV",
      "office": "Indonesia",
      "age": "42",
      "start_date": "2018-10-09"
    },
    {
      "id": "32",
      "first_name": "Juliane",
      "last_name": "Minchell",
      "address": "661 Bashford Parkway",
      "city": "Komiža",
      "phone": "240-242-2999",
      "email": "jminchellv@columbia.edu",
      "company_name": "Talane",
      "position": "Chemical Engineer",
      "office": "Croatia",
      "age": "59",
      "start_date": "2008-08-13"
    },
    {
      "id": "33",
      "first_name": "Tiertza",
      "last_name": "Fawdry",
      "address": "56 2nd Center",
      "city": "Navatat",
      "phone": "613-173-1832",
      "email": "tfawdryw@who.int",
      "company_name": "Babbleset",
      "position": "Executive Secretary",
      "office": "Philippines",
      "age": "45",
      "start_date": "1998-05-03"
    },
    {
      "id": "34",
      "first_name": "Gayla",
      "last_name": "Cauldfield",
      "address": "715 Pierstorff Parkway",
      "city": "Tiznit",
      "phone": "790-430-8635",
      "email": "gcauldfieldx@icio.us",
      "company_name": "Youbridge",
      "position": "Software Engineer I",
      "office": "Morocco",
      "age": "64",
      "start_date": "1987-02-19"
    },
    {
      "id": "35",
      "first_name": "Moritz",
      "last_name": "Ingley",
      "address": "5 Crescent Oaks Terrace",
      "city": "Houyu",
      "phone": "669-950-4060",
      "email": "mingleyy@hexun.com",
      "company_name": "Voonyx",
      "position": "Nuclear Power Engineer",
      "office": "China",
      "age": "38",
      "start_date": "1994-06-24"
    },
    {
      "id": "36",
      "first_name": "Thorin",
      "last_name": "Stedmond",
      "address": "51651 Doe Crossing Circle",
      "city": "El Ángel",
      "phone": "690-896-9746",
      "email": "tstedmondz@opensource.org",
      "company_name": "Shuffletag",
      "position": "Product Engineer",
      "office": "Ecuador",
      "age": "51",
      "start_date": "2010-06-13"
    },
    {
      "id": "37",
      "first_name": "Rudy",
      "last_name": "MacPaike",
      "address": "52053 Westend Avenue",
      "city": "Wangchang",
      "phone": "773-219-7683",
      "email": "rmacpaike10@forbes.com",
      "company_name": "Tazzy",
      "position": "Payment Adjustment Coordinator",
      "office": "China",
      "age": "51",
      "start_date": "2000-03-04"
    },
    {
      "id": "38",
      "first_name": "Anne-corinne",
      "last_name": "Kalinsky",
      "address": "75449 Bonner Drive",
      "city": "Asaita",
      "phone": "175-340-3781",
      "email": "akalinsky11@prnewswire.com",
      "company_name": "Katz",
      "position": "Operator",
      "office": "Ethiopia",
      "age": "48",
      "start_date": "2005-08-01"
    },
    {
      "id": "39",
      "first_name": "Logan",
      "last_name": "Clinning",
      "address": "64 Texas Hill",
      "city": "Atar",
      "phone": "250-717-2727",
      "email": "lclinning12@desdev.cn",
      "company_name": "Zoonder",
      "position": "Software Test Engineer IV",
      "office": "Mauritania",
      "age": "48",
      "start_date": "2017-07-05"
    },
    {
      "id": "40",
      "first_name": "Cayla",
      "last_name": "Mcwhinnie",
      "address": "60 Lukken Trail",
      "city": "Wabana",
      "phone": "473-323-2228",
      "email": "cmcwhinnie13@nytimes.com",
      "company_name": "Nlounge",
      "position": "Teacher",
      "office": "Canada",
      "age": "43",
      "start_date": "2000-04-23"
    },
    {
      "id": "41",
      "first_name": "Noll",
      "last_name": "Sacchetti",
      "address": "199 Kensington Avenue",
      "city": "Bang Rakam",
      "phone": "901-406-6246",
      "email": "nsacchetti14@globo.com",
      "company_name": "Lazzy",
      "position": "Physical Therapy Assistant",
      "office": "Thailand",
      "age": "32",
      "start_date": "1988-10-18"
    },
    {
      "id": "42",
      "first_name": "Harald",
      "last_name": "Morison",
      "address": "26 Sugar Court",
      "city": "Bobon",
      "phone": "102-234-4947",
      "email": "hmorison15@comcast.net",
      "company_name": "Wordware",
      "position": "Software Consultant",
      "office": "Philippines",
      "age": "51",
      "start_date": "2005-09-16"
    },
    {
      "id": "43",
      "first_name": "Hulda",
      "last_name": "Degoix",
      "address": "2 Grover Way",
      "city": "San José de Comayagua",
      "phone": "847-197-7128",
      "email": "hdegoix16@mapquest.com",
      "company_name": "Blogtags",
      "position": "Staff Scientist",
      "office": "Honduras",
      "age": "36",
      "start_date": "1995-08-29"
    },
    {
      "id": "44",
      "first_name": "Bernetta",
      "last_name": "Kennington",
      "address": "06248 Holy Cross Alley",
      "city": "Bokhan",
      "phone": "871-732-8191",
      "email": "bkennington17@devhub.com",
      "company_name": "Voonix",
      "position": "Teacher",
      "office": "Russia",
      "age": "36",
      "start_date": "1995-09-22"
    },
    {
      "id": "45",
      "first_name": "Anetta",
      "last_name": "Antushev",
      "address": "98 Riverside Plaza",
      "city": "Memphis",
      "phone": "901-129-0152",
      "email": "aantushev18@discovery.com",
      "company_name": "Meevee",
      "position": "Administrative Assistant II",
      "office": "United States",
      "age": "48",
      "start_date": "2013-06-05"
    },
    {
      "id": "46",
      "first_name": "Winslow",
      "last_name": "Forker",
      "address": "15621 Canary Court",
      "city": "Bačka Palanka",
      "phone": "156-115-4242",
      "email": "wforker19@drupal.org",
      "company_name": "Skilith",
      "position": "Speech Pathologist",
      "office": "Serbia",
      "age": "38",
      "start_date": "2018-05-07"
    },
    {
      "id": "47",
      "first_name": "Norry",
      "last_name": "Scholes",
      "address": "4619 Golf View Parkway",
      "city": "Changbu",
      "phone": "887-443-0913",
      "email": "nscholes1a@behance.net",
      "company_name": "Fivebridge",
      "position": "Clinical Specialist",
      "office": "China",
      "age": "29",
      "start_date": "2013-04-29"
    },
    {
      "id": "48",
      "first_name": "Jarad",
      "last_name": "Chiommienti",
      "address": "5 Autumn Leaf Avenue",
      "city": "Ust-Maya",
      "phone": "331-820-8115",
      "email": "jchiommienti1b@guardian.co.uk",
      "company_name": "Jabbercube",
      "position": "Structural Engineer",
      "office": "Russia",
      "age": "31",
      "start_date": "1992-01-05"
    },
    {
      "id": "49",
      "first_name": "Sherwynd",
      "last_name": "Traice",
      "address": "6 Amoth Avenue",
      "city": "Kalajoki",
      "phone": "364-559-1018",
      "email": "straice1c@123-reg.co.uk",
      "company_name": "Jaxnation",
      "position": "Graphic Designer",
      "office": "Finland",
      "age": "31",
      "start_date": "1987-06-14"
    },
    {
      "id": "50",
      "first_name": "Daveen",
      "last_name": "Brookwell",
      "address": "579 Walton Drive",
      "city": "Taodian",
      "phone": "358-903-2803",
      "email": "dbrookwell1d@pinterest.com",
      "company_name": "Meetz",
      "position": "Computer Systems Analyst II",
      "office": "China",
      "age": "28",
      "start_date": "1990-12-04"
    },
    {
      "id": "51",
      "first_name": "Krissie",
      "last_name": "Druett",
      "address": "1137 Rowland Trail",
      "city": "Bry-sur-Marne",
      "phone": "853-418-3077",
      "email": "kdruett1e@marriott.com",
      "company_name": "Oyondu",
      "position": "Staff Scientist",
      "office": "France",
      "age": "61",
      "start_date": "1996-06-23"
    },
    {
      "id": "52",
      "first_name": "Mervin",
      "last_name": "Fer",
      "address": "921 Mifflin Road",
      "city": "Orahovac",
      "phone": "637-138-7623",
      "email": "mfer1f@dropbox.com",
      "company_name": "Skajo",
      "position": "General Manager",
      "office": "Kosovo",
      "age": "62",
      "start_date": "1985-10-15"
    },
    {
      "id": "53",
      "first_name": "Manya",
      "last_name": "Cordery",
      "address": "972 Corscot Park",
      "city": "Naawan",
      "phone": "569-825-3385",
      "email": "mcordery1g@sphinn.com",
      "company_name": "Shuffletag",
      "position": "Desktop Support Technician",
      "office": "Philippines",
      "age": "51",
      "start_date": "1990-12-04"
    },
    {
      "id": "54",
      "first_name": "Rollins",
      "last_name": "Capstake",
      "address": "9356 Loftsgordon Parkway",
      "city": "Thị Trấn Mỹ Lộc",
      "phone": "171-718-2462",
      "email": "rcapstake1h@purevolume.com",
      "company_name": "Feedbug",
      "position": "Librarian",
      "office": "Vietnam",
      "age": "63",
      "start_date": "2007-10-22"
    },
    {
      "id": "55",
      "first_name": "Adolphe",
      "last_name": "Boken",
      "address": "53635 Jenna Circle",
      "city": "Xuanhua",
      "phone": "213-506-5895",
      "email": "aboken1i@nasa.gov",
      "company_name": "Brightbean",
      "position": "Research Assistant I",
      "office": "China",
      "age": "44",
      "start_date": "2000-12-12"
    },
    {
      "id": "56",
      "first_name": "Larisa",
      "last_name": "Tutt",
      "address": "6833 Clyde Gallagher Road",
      "city": "Tilburg",
      "phone": "374-995-4253",
      "email": "ltutt1j@yandex.ru",
      "company_name": "Camimbo",
      "position": "Mechanical Systems Engineer",
      "office": "Netherlands",
      "age": "50",
      "start_date": "2017-10-10"
    },
    {
      "id": "57",
      "first_name": "Cybill",
      "last_name": "Quipp",
      "address": "08810 Riverside Alley",
      "city": "Nerekhta",
      "phone": "917-834-4352",
      "email": "cquipp1k@gmpg.org",
      "company_name": "Mita",
      "position": "Food Chemist",
      "office": "Russia",
      "age": "56",
      "start_date": "1989-10-20"
    },
    {
      "id": "58",
      "first_name": "Bruno",
      "last_name": "Phin",
      "address": "20362 Jay Avenue",
      "city": "Manadas",
      "phone": "104-766-3271",
      "email": "bphin1l@histats.com",
      "company_name": "Meetz",
      "position": "Executive Secretary",
      "office": "Portugal",
      "age": "49",
      "start_date": "2001-12-29"
    },
    {
      "id": "59",
      "first_name": "Chryste",
      "last_name": "Wahlberg",
      "address": "418 Shopko Terrace",
      "city": "Dubu",
      "phone": "388-535-0269",
      "email": "cwahlberg1m@huffingtonpost.com",
      "company_name": "Centizu",
      "position": "Business Systems Development Analyst",
      "office": "China",
      "age": "60",
      "start_date": "2020-07-13"
    },
    {
      "id": "60",
      "first_name": "Morse",
      "last_name": "Playfair",
      "address": "43627 Blaine Circle",
      "city": "Kýria",
      "phone": "341-221-7265",
      "email": "mplayfair1n@addtoany.com",
      "company_name": "Blogspan",
      "position": "Project Manager",
      "office": "Greece",
      "age": "35",
      "start_date": "2009-11-20"
    },
    {
      "id": "61",
      "first_name": "Nadia",
      "last_name": "Lithgow",
      "address": "18 Montana Drive",
      "city": "President Roxas",
      "phone": "846-282-6148",
      "email": "nlithgow1o@odnoklassniki.ru",
      "company_name": "Trunyx",
      "position": "Quality Control Specialist",
      "office": "Philippines",
      "age": "26",
      "start_date": "2020-07-11"
    },
    {
      "id": "62",
      "first_name": "Salem",
      "last_name": "Domegan",
      "address": "1 Merry Court",
      "city": "Si Racha",
      "phone": "674-433-1077",
      "email": "sdomegan1p@reuters.com",
      "company_name": "Quire",
      "position": "Analog Circuit Design manager",
      "office": "Thailand",
      "age": "51",
      "start_date": "2007-03-28"
    },
    {
      "id": "63",
      "first_name": "Zilvia",
      "last_name": "Thouless",
      "address": "9679 Heffernan Street",
      "city": "Ambarakaraka",
      "phone": "573-281-7138",
      "email": "zthouless1q@flickr.com",
      "company_name": "Jetwire",
      "position": "Quality Engineer",
      "office": "Madagascar",
      "age": "38",
      "start_date": "1997-08-26"
    },
    {
      "id": "64",
      "first_name": "Fredric",
      "last_name": "Harmar",
      "address": "2386 Continental Lane",
      "city": "Dologon",
      "phone": "324-890-7529",
      "email": "fharmar1r@house.gov",
      "company_name": "Youtags",
      "position": "Sales Associate",
      "office": "Philippines",
      "age": "39",
      "start_date": "1990-12-06"
    },
    {
      "id": "65",
      "first_name": "Lesley",
      "last_name": "Folomkin",
      "address": "82 Arrowood Pass",
      "city": "Haiyangsuo",
      "phone": "721-557-9886",
      "email": "lfolomkin1s@studiopress.com",
      "company_name": "Aimbo",
      "position": "Physical Therapy Assistant",
      "office": "China",
      "age": "53",
      "start_date": "1985-09-18"
    },
    {
      "id": "66",
      "first_name": "Codie",
      "last_name": "Van der Merwe",
      "address": "55 Oak Point",
      "city": "Krasnohrad",
      "phone": "331-477-5286",
      "email": "cvandermerwe1t@time.com",
      "company_name": "Eayo",
      "position": "Recruiter",
      "office": "Ukraine",
      "age": "53",
      "start_date": "2007-08-06"
    },
    {
      "id": "67",
      "first_name": "Darcie",
      "last_name": "Minogue",
      "address": "1 Harper Drive",
      "city": "Panaitólion",
      "phone": "118-527-2076",
      "email": "dminogue1u@salon.com",
      "company_name": "Zoomcast",
      "position": "Web Developer IV",
      "office": "Greece",
      "age": "61",
      "start_date": "1988-09-15"
    },
    {
      "id": "68",
      "first_name": "Mathilda",
      "last_name": "O'Shiels",
      "address": "2 Swallow Crossing",
      "city": "Tianchi",
      "phone": "617-196-7972",
      "email": "moshiels1v@icq.com",
      "company_name": "Tagchat",
      "position": "Editor",
      "office": "China",
      "age": "64",
      "start_date": "2002-11-02"
    },
    {
      "id": "69",
      "first_name": "Loise",
      "last_name": "Firminger",
      "address": "894 Bay Avenue",
      "city": "Ágios Matthaíos",
      "phone": "430-443-9216",
      "email": "lfirminger1w@elegantthemes.com",
      "company_name": "Voolith",
      "position": "Financial Analyst",
      "office": "Greece",
      "age": "55",
      "start_date": "2002-09-12"
    },
    {
      "id": "70",
      "first_name": "Seth",
      "last_name": "Marmon",
      "address": "17 Twin Pines Alley",
      "city": "Bicos",
      "phone": "160-357-1228",
      "email": "smarmon1x@mayoclinic.com",
      "company_name": "Wikizz",
      "position": "Financial Analyst",
      "office": "Philippines",
      "age": "57",
      "start_date": "2010-03-27"
    },
    {
      "id": "71",
      "first_name": "Sydney",
      "last_name": "Rhead",
      "address": "39610 Boyd Street",
      "city": "Pisaras",
      "phone": "226-160-8937",
      "email": "srhead1y@virginia.edu",
      "company_name": "Dablist",
      "position": "Electrical Engineer",
      "office": "Micronesia",
      "age": "36",
      "start_date": "2001-05-26"
    },
    {
      "id": "72",
      "first_name": "Skippie",
      "last_name": "Gillinghams",
      "address": "94867 Jenifer Alley",
      "city": "Xuanbao",
      "phone": "583-974-2698",
      "email": "sgillinghams1z@vimeo.com",
      "company_name": "Aivee",
      "position": "Software Consultant",
      "office": "China",
      "age": "60",
      "start_date": "2007-08-24"
    },
    {
      "id": "73",
      "first_name": "Dorey",
      "last_name": "Woolham",
      "address": "6718 Lyons Drive",
      "city": "Erdao",
      "phone": "611-236-2984",
      "email": "dwoolham20@simplemachines.org",
      "company_name": "Feedmix",
      "position": "Compensation Analyst",
      "office": "China",
      "age": "29",
      "start_date": "2016-03-02"
    }
]
const number_of_buttons = 6;
const custom_header = [
    'Id', 
    'Nombre', 
    'Apellido', 
    'Dirección', 
    'Ciudad', 
    'Teléfono', 
    'e-mail',
    'Compañia', 
    'Posición', 
    'Oficina', 
    'Edad', 
    'Fecha inicio'
];

const refresh_button = document.getElementById('refresh-button');

refresh_button.addEventListener('click', async function(event) {
    event.preventDefault();
    //console.log(data);
    //Entry point
    builddatatable(data, number_of_buttons, custom_header);
})